### ISSUE TITLE
Enter needs to be pressed twice when searching

### ISSUE THREAD

**Issue by net** [laconalabs/LaconaApp#10]
The need to press enter twice when searching for something without specifying the search engine is annoying and a deal breaker.

<img width="1211" alt="screen shot 2016-01-29 at 7 19 57 pm" src="https://cloud.githubusercontent.com/assets/6983821/12691791/7c956770-c6bd-11e5-9348-a2e024bc2b52.png">

```
<first enter press>
```

<img width="1197" alt="screen shot 2016-01-29 at 7 20 20 pm" src="https://cloud.githubusercontent.com/assets/6983821/12691802/90572e2e-c6bd-11e5-8a08-f33d6a2bdf41.png">

```
<second enter press to search>
```

**Comment by brandonhorst** [comment]
This is an interesting case that I have put some thought into. If you don't specify a verb, there are 2 "fallthroughs" - `open` and `search`. If your goal is to open an application or a file, you really don't want to have to sort through a few dozen search engines to get to your app. And likewise, if you want to Google something, you don't want to accidentally open a file just because it happened contained your search term.

I don't know what the most elegant solution to this problem is. We could use some sort of `modifier key + enter` system, like Alfred uses, but I've always found that quite unintuitive. This is ultimately a design decision, and I will definitely keep thinking about. I would love to hear ideas from you all.

**Comment by net** [comment]
The problem here is that there is that `search <query>` doesn't have a default search engine. If the user wants to autocomplete to `search <query> on <search engine>` they can use `tab`, not `enter`.

**Comment by net** [comment]
Disappointed not to see this fixed in the latest release. I actually had to go back to using Alfred, as most of my `⌘ + space`ing is using google. I really want to use lacona, but it's not worth it for me if I have to press space twice every time I want to google something (or type "google " every time).

**Comment by brandonhorst** [comment]
It will come with time.

**Comment by Nxt3** [comment]
Yeah man, it's a beta. Lacona will slay Spotlight in time.

**Comment by net** [comment]
@Nxt3 Eh, I don't know about that. Spotlight is a search tool, Lacona is command tool.

**Comment by brandonhorst** [comment]
As of [Public Beta 3](https://github.com/lacona/LaconaApp/blob/54425cbe4f04bc1ec089ff2b825ffbd047085eea/CHANGELOG.md), for any input that is not a verb or the name of a file, app, bookmark, or url, "search for <input> on <search engine>" will show up first on the list. If you want to do a Google search, you will need to press return twice, but I have found that this is an acceptable cost of the reduction of visual complexity that comes from hiding the list of search engines behind the "search engine" placeholder.

If you want to search Google, you can always type "Google" before your input, or "on Google" after your input.

Lacona is more powerful than Alfred, and that does come with some trade-offs, especially for unqualified input (like fallthroughs). I think that over time, you'll find that pressing return twice doesn't hurt your productivity at all.

Thank you for the input.

**Comment by net** [comment]
I think the fallback here should be `search <query> on Google` (or a different user-set default search engine), instead of `search <query> on <search engine>`. If the user wants the specify a search engine for the query they can type `on`.

The question is, will the user be searching their default engine four or more times for every search they do on a non-default (it takes four key strokes to type `{space}on{space}`).  If they do, and I would imagine they do, then the single keystroke search is justified.

**Comment by brandonhorst** [comment]
Eventually, fallthroughs will be user-configurable. Then you will be able to set `"search Google for "` as the default fallthrough and it should work fine. For now, I think that this is an acceptable tradeoff.

**Comment by net** [comment]
Fair enough.
