### ISSUE TITLE
Assigning CMD+Space isn't possible

### ISSUE THREAD

**Issue by oskarkrawczyk** [laconalabs/LaconaApp#101]
A weird one. I've unassigned Spotlight from CMD+Space, and tried assigning it to Lacona, but it just ignores my input when trying to assign the new shortcut in the preferences. I can assign any other shortcut, but not this one.

**Comment by brandonhorst** [comment]
Hmmm... it works fine for me. Are you sure you don't have some other keyboard shortcut tied to CMD+Space?

**Comment by oskarkrawczyk** [comment]
I'm not 100% sure, but CMD+Space was assigned to Spotlight, and it was working fine. After disabling shortcut trigger nothing happens so I'd assume it's not being used by anything else... Unless it is and I just don't see it.

Feel free to close this issue, let's assume it's just a one-off issue with my setup.

**Comment by elithecho** [comment]
@oskarkrawczyk I was having the same issue but if you dig around the shortcuts you might see something latching on to CMD+Space

**Comment by oskarkrawczyk** [comment]
@choonggg I tried every trick in the book (and I'm a macOS power user). It really doesn't look like CMD+Space is latched to anything. I have no other ideas

**Comment by brandonhorst** [comment]
Is anybody else seeing this? Do other apps (like Alfred) or the Keyboard pref pane allow you to assign other things to CMD+Space?

**Comment by oskarkrawczyk** [comment]
Checked. Can't assign CMD+Space in Alfred, but can in Keyboard Preferences pane – but that probably supercedes anything on the OS.

It does look like something's latching to that shortcut, just can't figure out what it is.

**Comment by brandonhorst** [comment]
Unfortunately, I don't know of a tool to do that. You could perhaps try gradually quitting out of your running applications until you find something.

**Comment by brandonhorst** [comment]
Closing this for now, as it doesn't appear to be a Lacona issue. If you find what was causing it, please let me know and I'll add it to the FAQ that will exist at some point in the future.
