### ISSUE TITLE
Force "About Lacona" window to appear on top

### ISSUE THREAD

**Issue by slackmage** [laconalabs/LaconaApp#103]
No information is displayed when clicking this menu item.

**Comment by brandonhorst** [comment]
In my experience, it appears, just the windows sometimes shows up in the background. Not sure why. Is this what you are seeing? If you activate Mission Control, you should see a tiny window with the Lacona logo somewhere in the background.

**Comment by slackmage** [comment]
Gotcha. That's exactly what happened.

**Comment by brandonhorst** [comment]
Still something I want to fix. I'm going to change the title.

**Comment by slackmage** [comment]
Great! I'd fix it myself but close source :(

**Comment by brandonhorst** [comment]
All good!

**Comment by brandonhorst** [comment]
Fixed with [0.10.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Thanks!
