### ISSUE TITLE
Lacona does not display recently added applications to the applications folder

### ISSUE THREAD

**Issue by slackmage** [laconalabs/LaconaApp#105]
I've noticed this a couple times now. If you a) drag a newly downloaded app into the applications folder, b) then go to lacona and search for that app name, c) lacona will not be able to find it.

**Comment by brandonhorst** [comment]
Yeah - this is a known issue. The app index was only being built on startup. This has already been fixed and will be released with the next version. Thanks for reporting!

**Comment by brandonhorst** [comment]
Should be fixed with [0.10.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Check it out!
