### ISSUE TITLE
Keyboard shortcut indicators are cut off in results

### ISSUE THREAD

**Issue by sebj** [laconalabs/LaconaApp#109]
Keyboard shortcut indicators in search results look as though they're cut off by a few pixels at the top

![Screenshot](https://cloud.githubusercontent.com/assets/379991/16876934/e5de6ab0-4a9d-11e6-9875-1cf817947c7d.png)

**Comment by brandonhorst** [comment]
Could you report your screen size and resolution? Is this on a Macbook screen or external monitor?

**Comment by sebj** [comment]
This happens on an external monitor - 1920x1080 resolution, 23". On my Retina Macbook screen this doesn't happen though.

**Comment by brandonhorst** [comment]
That's the same report I got elsewhere - very interesting. I'll look into it. Thanks for reporting.

**Comment by brandonhorst** [comment]
So I was not actually able to reproduce this issue on my external monitor (same resolution), but I have a non-retina Macbook, so I suspect that was the issue. Beta 13 ([0.10.1](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md)) has a fix that I _think_ will fix it, but it would be great if you could upgrade and confirm for me.

Thanks!

**Comment by sebj** [comment]
Just updated, that appears to have fixed it for me (thanks!). I'll comment if anything changes though.

**Comment by brandonhorst** [comment]
Awesome, tahnks!
