### ISSUE TITLE
Request for settings options for old design without indentation

### ISSUE THREAD

**Issue by slackmage** [laconalabs/LaconaApp#111]
![fullscreen_7_15_16__11_01_am](https://cloud.githubusercontent.com/assets/230274/16878734/b9180bde-4a7b-11e6-99fb-a28e07d70e93.png)

Call me ocd but I liked the old design much better. The fonts were larger and that made locating the correct option faster.

**Comment by brandonhorst** [comment]
What do you mean by indentation? The only thing that changed is the font size (and the addition of icons of course).

**Comment by slackmage** [comment]
Hrmm could have sworn that was new. The smaller size feels too much like alfred/spotlight. I really preferred the old size for the speed of identification.

**Comment by brandonhorst** [comment]
With [1.0.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md), you can now change the font size (with the Large Fonts setting). Thanks for reporting!
