### ISSUE TITLE
Feature request: change audio output device with Lacona 

### ISSUE THREAD

**Issue by svennpetter** [laconalabs/LaconaApp#113]
Would love to be able to use lacona to change the audio output device

**Comment by brandonhorst** [comment]
This would make a great User Addon. Perhaps something could be built using the `audiodevice` command ([suggestion](http://apple.stackexchange.com/questions/213011/any-way-to-change-sound-output-device-via-applescript-or-shell)).

**Comment by brandonhorst** [comment]
This was released as `Change Audio Device` today.

**Comment by svennpetter** [comment]
Awesome! How do I use it?

**Comment by brandonhorst** [comment]
Preferences -> Addons -> Install New Addons -> Change Audio Device -> Install :)

![image](https://cloud.githubusercontent.com/assets/1938545/18693119/598570c2-7f6d-11e6-8a5b-3e5571656a73.png)

**Comment by brandonhorst** [comment]
Then you can use `change` 
![image](https://cloud.githubusercontent.com/assets/1938545/18693143/81fc0c78-7f6d-11e6-8b9b-7aad5d2ae48a.png)
