### ISSUE TITLE
Qualify Applications by path if there are multiple with the same name

### ISSUE THREAD

**Issue by slackmage** [laconalabs/LaconaApp#116]
Launching iTerm from Lacona but the app icon is crossed out and not launchable

![itermcantopen](https://cloud.githubusercontent.com/assets/230274/17058658/86f4437e-4fef-11e6-8f1b-955da386e86d.png)

**Comment by slackmage** [comment]
Should also mention:

I think I was able to do this before however.
iTerm is launchable via applications folder

**Comment by slackmage** [comment]
Thanks! 🙌🏻

**Comment by slackmage** [comment]
![about_this_mac_and__users_ian_desktop_cloud_dropbox_temp](https://cloud.githubusercontent.com/assets/230274/17058832/2dbe94ac-4ff0-11e6-9acc-359b87a5bc21.png)

**Comment by slackmage** [comment]
![about_this_mac_and__users_ian_desktop_cloud_dropbox_temp](https://cloud.githubusercontent.com/assets/230274/17058857/4e03f81a-4ff0-11e6-83e8-43c77041e93b.png)

**Comment by brandonhorst** [comment]
Very interesting. It works fine for me. Is it possible that you have multiple iTerms on your system? Try searching Spotlight and see if there are any in strange directories.

You could also try installing the `lacona-find` addon and then running `find iTerm`, which should give the same information.

**Comment by slackmage** [comment]
You're right on the money with that guess. Here we go.

![screenshot_7_22_16__2_02_pm](https://cloud.githubusercontent.com/assets/230274/17066424/0275fd88-5015-11e6-99d9-2ae6eb41dbcd.png)

Looks like SageMath had a copy of iterm bundled in the download. 

Maybe it bests to show both in that case even though they both have the same application name?

**Comment by brandonhorst** [comment]
Definitely. I'm going to change the title of this issue, and I will definitely fix it.

**Comment by slackmage** [comment]
Ok, it seems that an update to osx latest (10.11.6) and a lacona update has fixed this issue somehow. There is still two iterm apps on the fs, but only the one in the applications folder displays in a lacona search.

**Comment by brandonhorst** [comment]
The behavior is likely undefined - right now, it's just going to use whichever Spotlight returns first, and Spotlight results are (I believe) ordered randomly.

**Comment by slackmage** [comment]
Right. Though the Newest osx must have known somehow that the execution-disabled app was bad. 

Thanks to SageMath for randomly putting a bogus iTerm.app on my fs.

![robot_head_frustrated](https://cloud.githubusercontent.com/assets/230274/17078895/e46c9a72-50cd-11e6-8f57-8d5cef5573a7.gif)

**Comment by brandonhorst** [comment]
I'm actually going to leave this open, just for my own sake, until I release the qualifier. Thanks!

**Comment by slackmage** [comment]
Sure thing. Thanks for the help. Lacona's great.

**Comment by brandonhorst** [comment]
Added application qualifiers with [1.0.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md), so this shouldn't happen again! Thanks for reporting!

**Comment by slackmage** [comment]
Thanks Brandon!
