### ISSUE TITLE
after calculation, styling is messed up

### ISSUE THREAD

**Issue by jeffshaver** [laconalabs/LaconaApp#118]
The image kind of explains it. heres how I got to the the point in the image:
1. open lacona (cmd + space)
2. type a number (i typed 8)
3. backspace
4. the result is in the screenshot below

<img width="715" alt="screen shot 2016-07-25 at 9 59 00 pm" src="https://cloud.githubusercontent.com/assets/5390616/17123673/3075b958-52b3-11e6-889c-0914da7b31ba.png">

**Comment by brandonhorst** [comment]
Thanks for reporting. I've seen this issue before, though I've never been able to reproduce it properly. Could you report your computer model & screen size?

**Comment by brandonhorst** [comment]
Should be Fixed with [1.0.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Thanks for reporting!
