### ISSUE TITLE
alfred-workflows

### ISSUE THREAD

**Issue by ivikash** [laconalabs/LaconaApp#119]
Can we incorporate https://github.com/zenorocha/alfred-workflows in lacona too? eg - emoji, colorcode, caniuse would be very helpful 👍

**Comment by brandonhorst** [comment]
Yes!

So Lacona of course cannot run Alfred workflows directly, but it is more than powerful enough to re-implement all of them as addons. I will gradually be creating more addons, and hopefully other users will get involved too. [Docs here](http://docs.lacona.io/).

If you have specific features that are important to you, please open them up as individual issues so they can be tracked, commented on, and assigned independently. But I hope that before too long, all of these tools will be up and running in Lacona!
