### ISSUE TITLE
Two finger scrolling moves the actual bar window

### ISSUE THREAD

**Issue by net** [laconalabs/LaconaApp#12]
Two finger scrolling (trackpad, or one finger on the magic mouse) will move the bar window up/down on the screen if there is no content to be scrolled. I'm not sure if this also happens with the scroll wheel on normal mice.

**Comment by brandonhorst** [comment]
Added with https://github.com/lacona/LaconaApp/releases/tag/0.3.1 - "Check for Updates..." to download it now!
