### ISSUE TITLE
Calculate command intermittently fails

### ISSUE THREAD

**Issue by sebj** [laconalabs/LaconaApp#121]
In the process of typing this, I started with 'calculate command does not support decimals' as that's what I thought, but it appears that the calculate command just intermittently fails – whether I start typing immediately after opening Lacona, or if I backspace a character (the popover does not update, or just disappears entirely).

Could this be related to the calculate command doing math asynchronously?

**Comment by brandonhorst** [comment]
This is not behavior I've ever seen before. Occasionally there is a pause before the result appears, but I've never seen it fail to appear entirely (for a valid query).

Could you send me the contents of `~/Library/Logs/Lacona/app.log` so I can check if an error is occurring with the command? Thanks.

**Comment by sebj** [comment]
Not sure it's worth sending the log – currently has "JS disconnected from server" on 4 lines and nothing else.

Also, I cannot recreate this any more after rebooting. I thought reordering 'Automatic Prefixes' in the 'Shortcuts' section of preferences fixed the problem, but even the default order is fine now.

Sorry for wasting your time I guess, this was bugging me _a lot_ this morning..
