### ISSUE TITLE
Not enough whitespace between fallback verbs and the rest of the query

### ISSUE THREAD

**Issue by net** [laconalabs/LaconaApp#13]
<img width="93" alt="screen shot 2016-01-29 at 7 46 28 pm" src="https://cloud.githubusercontent.com/assets/6983821/12692114/1ced8ede-c6c1-11e5-845b-517ef403143f.png">

This might just be me, but it feels uncomfortable how little space there is between the blue verb box and the next word.

**Comment by brandonhorst** [comment]
I agree.

**Comment by brandonhorst** [comment]
Added with https://github.com/lacona/LaconaApp/releases/tag/0.3.1 - "Check for Updates..." to download it now!

**Comment by net** [comment]
Now there's not enough space between the verb and the border of the grey box.

<img width="51" alt="screen shot 2016-02-01 at 9 02 26 am" src="https://cloud.githubusercontent.com/assets/6983821/12719362/926fd164-c8c2-11e5-88b6-18359f8b10a9.png">

**Comment by brandonhorst** [comment]
Right now, it's exactly where I want to to be. When you're drawing lines between words, you don't have a lot of space to work with - I think it's in a good location.

If I was going to change this, it would be to change the entire appearance for "fallthrough" verbs - if you have a recommendation, please let me know.

**Comment by net** [comment]
I think this is a comfortable amount of whitespace:

<img width="717" alt="screen shot 2016-02-01 at 9 55 55 am" src="https://cloud.githubusercontent.com/assets/6983821/12720771/4c6ccf0c-c8ca-11e5-96c7-ba7a625f0d14.png">

Perhaps you could add 3 or 4 spaces between fallback verbs and the query to give more room for the line?

**Comment by brandonhorst** [comment]
So the issue with that is when you press the `tab` key. The advantage of the current system is that currently, pressing tab essentially just removes the fallthrough but everything stays in its place. If you add some spacing there, then you get everything jumping over to the left when you press tab, which is an effect which I'm not thrilled with.

**Comment by net** [comment]
I see what you're saying. Maybe just don't highlight fallback verbs? They're never shown at the same time as non-fallback verbs anyways. Or highlight them in a color, rather than giving them a background?
