### ISSUE TITLE
Purchase Lacona dialog - Bug

### ISSUE THREAD

**Issue by ghost** [laconalabs/LaconaApp#130]
To reproduce:
1. Click "Purchase Lacona..."
2. Switch to another app (e.g., to get the email address...)
3. Not really a bug, but poor usability here, because there's no window anymore, so we have to:
4. Click "Purchase Lacona..." again
5. Click "Cancel" button — doesn't work — Bug
6. Click "Quit" to exit Lacona — doesn't work — Bug
7. Also, after clicking "Purchase Lacona..." a few times, Lacona quits unexpectedly.

**Comment by brandonhorst** [comment]
This should be fixed with [1.0.3](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Check for updates and it should be fixed. Sorry about that! Thanks for reporting!
