### ISSUE TITLE
Control Apple Music with `play` command

### ISSUE THREAD

**Issue by Misophistful** [laconalabs/LaconaApp#131]
The `play` command only appears to search your local iTunes music. Would it be possible to extend the functionality to also search the Apple Music service, and play the chosen artist/album/song from there?

**Comment by brandonhorst** [comment]
Not possible, unfortunately. Apple has not released a API on macOS (there is one on iOS). 

I am in the process of building a Spotify addon, which is possible. And if Apple ever opens this up, I'd love to see it supported.

**Comment by Misophistful** [comment]
Understood. Thanks for letting me know.

**Comment by HansWurst90** [comment]
@brandonhorst Is there a way to be informed when a spotify integration is available?

**Comment by brandonhorst** [comment]
@HansWurst90 Subscribe to the [mailing list](http://eepurl.com/bjPRjD) or follow on [twitter](http://twitter.com/lacona).
