### ISSUE TITLE
There is no option to remove this app form my mac. 

### ISSUE THREAD

**Issue by themefisher** [laconalabs/LaconaApp#134]
Its really frustrating that there is no available option to remove this app.Please give me a way.
Thanks

**Comment by brandonhorst** [comment]
I'm sorry? You can uninstall the app exactly the same way you uninstall every other (non-App Store) app - quit it and drag it to the trash.

**Comment by themefisher** [comment]
Then How Can I remove this ? I asked to how to remove and you answered that I can not remove ? I really want to remove this app .

**Comment by brandonhorst** [comment]
I don't understand what you mean. Just quit the app, then drag the app from your Applications directory to the trash.
