### ISSUE TITLE
Support for changing Alt + (number) to a different modifier

### ISSUE THREAD

**Issue by net** [laconalabs/LaconaApp#14]
For example, ⌘ + (number) like Alfred.

<img width="70" alt="screen shot 2016-01-29 at 7 53 32 pm" src="https://cloud.githubusercontent.com/assets/6983821/12692248/8408a756-c6c2-11e5-885e-d333c4825105.png">

**Comment by brandonhorst** [comment]
This is now possible in [1.1.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Thanks for requesting!
