### ISSUE TITLE
Convert to user's currency if input matches Lacona default currency

### ISSUE THREAD

**Issue by sebj** [laconalabs/LaconaApp#141]
I'm in the UK, with default currency set to USD. But if I type "100 usd" I see "100 USD = 100 USD" which isn't very helpful. Would be great to automatically use the currency of the user's country if they're converting from the default in Lacona settings.

**Comment by brandonhorst** [comment]
I crossposted this on https://github.com/brandonhorst/lacona-convert-currency/issues/2
