### ISSUE TITLE
Caffeinate in 1.1.1 Not working

### ISSUE THREAD

**Issue by ghost** [laconalabs/LaconaApp#143]
Tried using `caffeinate` and the `caffeinate for [time]` but screensaver still comes on. 

Is there some setting I am overlooking that would prevent it from working effectively?

**Comment by brandonhorst** [comment]
Good find - it was preventing sleep but not screensaver.

Should be fixed. Go to the Addons page, click "Check for Updates", and then click the green update button next to the Caffeinate addon on the left.
