### ISSUE TITLE
"Launch at Login" feature not working

### ISSUE THREAD

**Issue by oalhait** [laconalabs/LaconaApp#148]
Every time I log out/log back in or restart my computer, I have to manually open Lacona, as it doesn't open on login. Is there any way I can fix this? Is this happening with other users? I'm getting this error on my retina Macbook Pro on macOS Sierra (but I had this problem when I was running El Capitan too). My Lacona version is 1.1.2.

**Comment by rbeeger** [comment]
Noticed this also. I now put Lacona manually into the group of apps to automatically launch at each login (Preferences > Users & Groups > login objects - or something like that. My notebook runs on German. So it's Anmeldeobjekte here). Haven't rebooted by MacBook yet, but I guess that should do it.

**Comment by oalhait** [comment]
@rbeeger thanks for the heads up, I didn't think to add it to the list of apps to start on login. However, I feel like this shouldn't need a workaround. There are a good amount of tutorials ([this one](https://blog.timschroeder.net/2012/07/03/the-launch-at-login-sandbox-project/) is a good example) to get your mac app to launch on login. Hopefully this will be patched up by the next update, because it shouldn't be that hard to make the fix.

**Comment by brandonhorst** [comment]
You're right - oversight with 1.1.0 that I missed in my tests. Sorry about that! A fix will be coming soon.

**Comment by brandonhorst** [comment]
Fixed in 1.1.3. Sorry about that!
