### ISSUE TITLE
Ctrl or Option + HJKL navigation

### ISSUE THREAD

**Issue by bezhermoso** [laconalabs/LaconaApp#15]
It would be nice to be able to navigate through Lacona with `vi` bindings, like LaunchBar. :)

**Comment by brandonhorst** [comment]
I like it.

**Comment by net** [comment]
+1

**Comment by brandonhorst** [comment]
Added with https://github.com/lacona/LaconaApp/releases/tag/0.3.1 - "Check for Updates..." to download it now!
