### ISSUE TITLE
Window opening only in desktop

### ISSUE THREAD

**Issue by whit-colm** [laconalabs/LaconaApp#156]
When I trigger Lacona, it only opens in my desktop, even if I am in a different fullscreen app (for instance, Safari.) I am running a beta so I do not know if this is an issue caused by that, but either way, I feel it is important for you guys to know.

Also, sweet app!

**Comment by brandonhorst** [comment]
Thanks! Duplicate of https://github.com/laconalabs/LaconaApp/issues/42.
