### ISSUE TITLE
"calculate" command to do basic arithmetic

### ISSUE THREAD

**Issue by brandonhorst** [laconalabs/LaconaApp#16]

**Comment by kopischke** [comment]
Again, this is something Spotlight already does. That doesn’t mean Lacona should not implement the feature, but it raises the question if Lacona is meant to _replace_ Spotlight or to _complement_ it? El Capitan’s Spotlight is quite the powerful and well designed information retrieval application, making me wonder if duplicating its features isn’t time wasted that would better be spent on the kind of superior command UX Spotlight does not try to provide.

**Comment by brandonhorst** [comment]
That is an excellent question. I think that long-term, the answer needs to be "replace Spotlight." The ultimate goal is "whatever you want to do, just type it into Lacona." Forcing user to think "Use Lacona unless I want to do math define a word" (or something like that) is just a bad experience, especially because the things that Spotlight can do are relatively few and easy to implement.

That said, there is a reason why I haven't made this a huge priority thus far - the initial goals should be to do stuff that Spotlight can't do before we focus on replicating technology.

So this will come, though perhaps not for a while.

**Comment by hadifarnoud** [comment]
when I enter a normal (2000+40000)/2, I expect it to give me a number not search on google.

don't make me enter a command like `calc` before those equations.

**Comment by brandonhorst** [comment]
Added with [0.10.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Thanks!
