### ISSUE TITLE
Can't use bash aliases when using the Shell Commands addon

### ISSUE THREAD

**Issue by sgrgrsn** [laconalabs/LaconaApp#160]
Hello there. I am using Lacona through Setapp, and having a question regarding the Shell Commands addon.

I am not able to use my aliases defined in the .bash_profile on macOS - is it possible to enable it somehow? When I try to run a command alias I get a notification saying:

**Shell** 
_Error executing shell command_

**Comment by brandonhorst** [comment]
Shell Commands does not spawn up a bash shell, and therefore `.bash_profile` will never be accessed.

A future version of Shell Commands will be able to open commands in the Terminal, rather than running them outright, but it is not currently possible.
