### ISSUE TITLE
Don't ask for search engine when there is only one

### ISSUE THREAD

**Issue by dmo-odoo** [laconalabs/LaconaApp#163]
Hello,

I've been looking for a way to enhance my spotlight experience and I found Lacona, great job here !

However, it does have a small issue that prevents me from doing the thing I wanted to do most:
I have to press enter twice to launch a web search even though I deleted all the search engines except one.

Basically what I would like to do is navigate the web using DuckDuckGo bangs but from within my Spotlight-replacement itself. The goal is to keep using the syntax that I have been using within Chrome (with DuckDuckGo) except that I don't have to have Chrome already open for it to work and the shortcut would be the same one to open an application and open a webpage since everything would be done through Lacona.

Lacona neaaarly allows me to do this, except that it requires me to press enter twice to make a web search with the only search engine I have... ;-)

Thank you,
David

**Comment by brandonhorst** [comment]
The next version of Lacona will do this automatically! Thanks for the request!
