### ISSUE TITLE
Can't find Applications anymore

### ISSUE THREAD

**Issue by dmo-odoo** [laconalabs/LaconaApp#166]
Hello,

Sometimes, Lacona is unable to find apps, like I write "atom" but it doesn't suggest "open Atom". Even if I write "open atom" it doesn't suggest it. Only the preferences panes, folders, bookmarks etc are suggested.

I usually solve this by killing then restarting Lacona, but I think it would be better that it works... :p
I'm ok to test anything when this happens next if you need me to if you can't reproduce it on your machine... ;-)

Best regards,
David

**Comment by sevans-ge** [comment]
I'm running into a similar issue. "Microsoft Outlook" refused to be found by Lacona anymore, despite all the other Microsoft apps being suggested. Restarting Lacona doesn't seem to help in my case though.

**Comment by brandonhorst** [comment]
Hi folks - sorry for the delay on this. This is a known issue, due to a quirk with how some Microsoft products and Spotlight interact, along with some poor code on my end. It will be fixed in the next release, which is hopefully coming soon!

**Comment by dmo-odoo** [comment]
Hello @brandonhorst, are you sure this is related to my original issue ? Atom is not a Microsoft product, but I may be misunderstanding your comment... ;-)

**Comment by brandonhorst** [comment]
This has been fixed 1.1.4. Thank you!
