### ISSUE TITLE
High Sierra

### ISSUE THREAD

**Issue by SteveGSY** [laconalabs/LaconaApp#169]
Not loading on OSX High Sierra

**Comment by apetrovs** [comment]
+1
Lacona launch logs from Console.app in attachment
[console.txt](https://github.com/laconalabs/LaconaApp/files/1196666/console.txt)
[system.txt](https://github.com/laconalabs/LaconaApp/files/1196667/system.txt)

**Comment by brandonhorst** [comment]
Thank you! Pushing a fix to this before full launch.

**Comment by brandonhorst** [comment]
This has been fixed 1.1.4. Thank you!

**Comment by jdehnert** [comment]
Brilliant!  Works for me.
