### ISSUE TITLE
Load time?

### ISSUE THREAD

**Issue by QuadDepo** [laconalabs/LaconaApp#173]
Sometimes when i open lacona, I start typing right away.

Sometimes when i type

`open iterm` or `open chrome` it has a big delay and I have to go all the way back to typ open again.

Anyone else having this aswell? #

**Comment by brandonhorst** [comment]
Lacona does need to cache some spotlight searches before it starts working, and the spotlight search time can be a bit inconsistent. I would recommend launching Lacona at startup and you likely won't have this issue.

**Comment by QuadDepo** [comment]
Ah oke, i will check it out thanks :-)
