### ISSUE TITLE
Dark mode shows white borders

### ISSUE THREAD

**Issue by sergeh** [laconalabs/LaconaApp#178]
Currently on Mojave, when dark mode is set, Lacona shows a white border 

![screen shot 2018-10-31 at 11 00 51 am](https://user-images.githubusercontent.com/80928/47797382-9b4a3080-dcfc-11e8-8f96-e9a5ef1cded3.png)

**Comment by brandonhorst** [comment]
Could you send me your screen resolution? And is this a Retina display?

**Comment by brandonhorst** [comment]
This has been fixed in [Lacona 2](https://lacona.app).
