### ISSUE TITLE
Can't turn on reminders or calendar access

### ISSUE THREAD

**Issue by help-for-me** [laconalabs/LaconaApp#179]
For some reason when I first installed Lacona, all features were turned on except for events and reminders. It will not let me turn these on.
https://imgur.com/a/6BLCZXt

**Comment by mutantant** [comment]
Same situation here. The settings plist file has them disabled as well. When I enable them in the plist, they are set back to disabled as soon as the app is launched.

Related: Lacona does not show up on the security pane under Contacts or Calendar as an app that has access, nor does it ask for access when first launched.

MacBook Pro 13" 2014 running Mojave.

EDIT: Sorry, I misspoke, it does ask for all access in a single box on first launch, but the OS doesn't follow up with individual "Allow Lacona to access Contacts" kinds of dialogs after, so I'm assuming for some reason it isn't flagging as needing those abilities in the OS.

**Comment by brandonhorst** [comment]
This appears to be affecting only the Setapp version, and only on MacOS 10.14.2. It's either due to an undocumented change with 10.14.2, or an issue with Setapp itself.

Just to confirm, are you seeing these issues on the Setapp version?

**Comment by brandonhorst** [comment]
I understand the problem and will be releasing a fixed version shortly.

**Comment by brandonhorst** [comment]
A fix was just submitted to SetApp and will be rolling out shortly.

**Comment by bishless** [comment]
Seems the issue still persists in the SetApp version (Lacona 1.1.6) on macOS 10.4.3.

I can't enable any of the Contact indexing options nor Create Reminders.

**workaround**: I was able to manually grant Lacona permission to Contacts and Reminders via System Preferences > Security & Privacy > Privacy tab.

**Comment by help-for-me** [comment]
Hmm that’s too bad because otherwise I would really enjoy using this app.

Thanks,
Michael

**Comment by brandonhorst** [comment]
This has been fixed in [Lacona 2](https://lacona.app).
