### ISSUE TITLE
Unable to "empty Trash"

### ISSUE THREAD

**Issue by ghost** [laconalabs/LaconaApp#180]
I am not able to empty trash.

**Comment by brandonhorst** [comment]
My suspicion is that Lacona is not able to use "System Events Automation", a control added in macOS 10.14 Mojave.

If you are using the SetApp version of the app, I suspect that you were not prompted to give permission due to #179. I am investigating the issue.

**Comment by brandonhorst** [comment]
I've confirmed that this is caused by the same problem as #179. I'm closing this as a duplicate, and I have a fix for that issue.
