### ISSUE TITLE
Error executing shell command?

### ISSUE THREAD

**Issue by beib** [laconalabs/LaconaApp#181]
I’m having trouble running terminal command via lacona, and would appreciate some help.

This is the simple line that I tried `run touch test.txt in` After that, there is a prompt to create in an open folder, which I selected. But Lacona says "Error executing shell command”. 

Could you let me know how I can make it work?

**Comment by brandonhorst** [comment]
There seems to be an issue with the "in" argument. I'll investigate.

**Comment by brandonhorst** [comment]
This is fixed. Update lacona-shell to 1.2.0 and this should work for you. Thanks for reporting!
