### ISSUE TITLE
Open app feature not work properly on MacOS Catalina

### ISSUE THREAD

**Issue by mingjun97** [laconalabs/LaconaApp#182]
I upgraded my MacOS to Catalina developer beta version. It seems that the open feature doesn't work for system built-in application such as `Mail`, `System Preference`. It does work for some third-party application.

![image](https://user-images.githubusercontent.com/15214491/59810782-b1bcf080-92bb-11e9-878f-07d3e02c8e21.png)

![image](https://user-images.githubusercontent.com/15214491/59810802-c4372a00-92bb-11e9-8854-9fad3f98078e.png)

OS Version: 15.15 Beta (19A487l)

**Comment by brandonhorst** [comment]
I'll investigate, thanks for the report.

**Comment by brandonhorst** [comment]
I can reproduce this. There appears to be some new permission required to list Applications. For example, running `ls /Applications` from the Terminal seems to list the same subset of Applications.

Searching for a solution now.

**Comment by mingjun97** [comment]
Thanks for reply. I‘ve granted it as full disk access. But it seems doesn’t work. I’m not sure if it’s something wrong with Beta version.

**Comment by Hitchhik3r** [comment]
I'm running into similar issues. Various apps no longer show up when typing open "application". Please keep us updated. Thanks.

**Comment by anaday** [comment]
Update: Sorry for the false alarm. It just it occurred to me that I disabled Spotlight some time ago. Reenabling it fixed my issue.

I just "discovered" Lacona and installed from Homebrew. I am experiencing the same. None of my applications -- system or regular apps -- are showing up. I am on High Sierra.

Great app btw. I'm looking to replace Quicksilver.

**Comment by brandonhorst** [comment]
Looks like Apple moved many of the built-in apps to `/System/Applications` in Catalina. They still show up in `/Applications` in Finder, but not in Terminal.

You can make this work properly by adding `/System/Applications` to the "Application Search Directories" setting, under "macOS Integration".

I'll be putting out a fix soon. Sorry for the inconvenience!

<img width="972" alt="image" src="https://user-images.githubusercontent.com/1938545/66092182-fd3c9700-e558-11e9-8450-1c9b14cf644f.png">
