### ISSUE TITLE
"Error fetching audio ports" on Catalina

### ISSUE THREAD

**Issue by beib** [laconalabs/LaconaApp#184]
This error pops up after upgrading to Catalina. Switch audio ports is not currently working.

**Comment by gxjansen** [comment]
Same issue here

**Comment by ApolloGama** [comment]
I have been getting the same error as well

**Comment by lmenale** [comment]
same issue

**Comment by brandonhorst** [comment]
This feature relies on an API which has been removed.

I'll build this feature in [Lacona 2](https://lacona.app) with an alternative API, if possible.
