### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by DeLoeribas** [laconalabs/LaconaApp#187]
The `calculate` command does not accept localized entries. You can enter `1.5 * 10`, but many regions use a comma as separator. Lacona does not recognise `1,5 * 10`.
At least it should accept a point (.) and comma (,) as decimal separator in calculations.

**Comment by brandonhorst** [comment]
Noted. [Lacona 2](https://lacona.app) uses Soulver for its calculation, so this should be very straightforward possible. I've made a note.
