### ISSUE TITLE
Can not install addons on Lacona.

### ISSUE THREAD

**Issue by BH-M87** [laconalabs/LaconaApp#188]
When I tried to install addons on Lacona, I met a problem as the picture show:
<img width="524" alt="CleanShot 2019-12-10 at 03 41 17@2x" src="https://user-images.githubusercontent.com/16903266/70507650-bf1aaf80-1b67-11ea-88fd-16fc232ee05e.png">

With message:
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN lifecycle npm is using /Applications/Setapp/Lacona.app/Contents/Resources/bin/lacona-node but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
sh: node: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! core-js@2.6.11 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the core-js@2.6.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuxuheng/.lacona-npm/_logs/2019-12-10T02_05_31_558Z-debug.log

The core of this message is:
sh: node: command not found

But I have install node on my computer:
> $ node -v                                                                                      ⬡ 10.16.0 
v10.16.0

Could you please help me to solve this problem?
I have tried reinstall Lacona several times.

**Comment by TomL-J** [comment]
I was going to post something along these lines too. Rather frustrating, as the addons look useful.

**Comment by BH-M87** [comment]
> I was going to post something along these lines too. Rather frustrating, as the addons look useful.

So sad..Have you fixed this problem now?

**Comment by Nerwin** [comment]
looks like Lacona is not maintained anymore ...

**Comment by farzado** [comment]
@TomL-J  @BH-M87 To install the addons, first make sure Node is installed on your machine (assuming it's in /usr/local/bin/node), then close the Lacona app and run it from command line using `./Lacona --scripts-prepend-node-path /usr/local/bin/node`.

**Comment by orthodoX** [comment]
I am also experiencing the issue. @farzado The solution above kinda works, but not as expected. First of all the command above will launch a completely new instance of Lacona that needs to be configured again. The plugins can be installed, but then I experienced that some of the default features like calls or reminders stopped working 😞 

@brandonhorst Any suggestions regarding this one?

**Comment by brandonhorst** [comment]
This should be fixed as of 1.1.8 (released today). Sorry for the delay!

Lacona v2 will be released this month (pending Apple's approval), and will be more modern without these bugs. Sorry!

**Comment by BH-M87** [comment]
Good news!

**Comment by orthodoX** [comment]
@brandonhorst Epic news! ❤️ I guess the v2 release will also be available through Setapp at the same time?

**Comment by BH-M87** [comment]
Updated, but still can not work.

Connection problem?

npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! fetch failed https://registry.npmjs.org/core-js/-/core-js-2.6.11.tgz
npm WARN retry will retry, error on last attempt: Error: connect ECONNABORTED 104.16.22.35:443 - Local (0.0.0.0:0)
npm ERR! fetch failed https://registry.npmjs.org/core-js/-/core-js-2.6.11.tgz
npm WARN retry will retry, error on last attempt: Error: connect ECONNABORTED 104.16.22.35:443 - Local (0.0.0.0:0)
npm ERR! fetch failed https://registry.npmjs.org/core-js/-/core-js-2.6.11.tgz
npm ERR! unpack Could not read data for core-js@2.6.11
npm ERR! code ECONNABORTED
npm ERR! errno ECONNABORTED
npm ERR! syscall connect
npm ERR! connect ECONNABORTED 104.16.22.35:443 - Local (0.0.0.0:0)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuxuheng/.lacona-npm/_logs/2020-04-02T08_14_41_558Z-debug.log
