### ISSUE TITLE
System Preferences "Dark Mode" not working from Setapp.

### ISSUE THREAD

**Issue by TomL-J** [laconalabs/LaconaApp#189]
I can use other System Preferences ok but Dark Mode just doesn't work either enabling it or disabling it. This is on the Setapp version.

**Comment by Ellana42** [comment]
I'm having de same issue

**Comment by ivomota** [comment]
Same here!

**Comment by brandonhorst** [comment]
Unfortunately this API is no longer available as of macOS Catalina. This feature has been removed from [lacona 2](https://lacona.app).
