### ISSUE TITLE
triggering lacona loses focus to the original application

### ISSUE THREAD

**Issue by Linerd** [laconalabs/LaconaApp#20]
This doesn't happen with alfred. When you trigger Lacona and then close it, the focus is not on the original application, which is a quite unpleasant

**Comment by Linerd** [comment]
Thanks for the quick reaction. When is the full release btw?

**Comment by brandonhorst** [comment]
Hopefully March, though I'm not setting a firm date yet.

I've fixed this, it'll be in the next release.

**Comment by brandonhorst** [comment]
Added with https://github.com/lacona/LaconaApp/releases/tag/0.3.1 - "Check for Updates..." to download it now!
