### ISSUE TITLE
Should the selection bar match the system color?

### ISSUE THREAD

**Issue by brandonhorst** [laconalabs/LaconaApp#22]
I want some feedback. I want the interface to fit in with the system as much as possible. I am toying around with the idea of having the selection bar match the system selection bar color (blue by default). OSX, when displaying a selected item with a blue background, shows the text in white. Here's an example from Spotlight

![image](https://cloud.githubusercontent.com/assets/1938545/12705339/dc51caf6-c83d-11e5-8fa0-2409e19a72a2.png)

However, Lacona is a colorful interface and this doesn't really work. Inverting or lightening the colors would look very strange. So I can see two options - either don't do this and use a generic-color selector, or only show the selection indicator on a portion of the bar.

I've attached some pictures (from the yet-unreleased Light Mode Theme, because I think it demonstrates the problem better). Which one do you prefer and why?

How it works now - darken the bar, but only slightly so as not to wreck the contrast.

![image](https://cloud.githubusercontent.com/assets/1938545/12705350/4e591050-c83e-11e5-9d29-12189e3272d9.png)

Use a colored bar on the left side to indicate selection.

![image](https://cloud.githubusercontent.com/assets/1938545/12705335/96ac0c28-c83d-11e5-9277-b5b9fa2512c7.png)

**Comment by quigebo** [comment]
darker bar feels more intuitive and easier to understand

**Comment by yadomi** [comment]
I think it's a good idea to have a light theme that match the system color. The first screenshot looks good to me as the second doesn't feel intuitive.

Personally, I use **f.lux** to switch system color, that would be great to have lacona changes his colors according to system.

**Comment by Nxt3** [comment]
The first one seems best.

**Comment by brandonhorst** [comment]
Thanks for the feedback. I chose option 1 for https://github.com/lacona/LaconaApp/releases/tag/0.3.1
