### ISSUE TITLE
brew cask apps aren't detected to be opened as an Application

### ISSUE THREAD

**Issue by brandonhorst** [laconalabs/LaconaApp#23]
_From @agustifernandez on January 31, 2016 6:26_

I am not able to find my brew cask installed apps with Lacona.

Here is the equivalent of this issue on brew cask's repo in relation to alfred [caskroom/homebrew-cask Installed apps can't be found by Alfred (issue #4327)](https://github.com/caskroom/homebrew-cask/issues/4327)

I guess an mvp of this would be some way to add path's to lacona's indexing scope, that way you don't solve the problem of apps installed via cask brew not showing up out of the box, but you potentially let others find out which path's they would include by default.

_Copied from original issue: lacona/lacona#10_

**Comment by brandonhorst** [comment]
Moving this to LaconaApp.

**Comment by brandonhorst** [comment]
Yeah, this is a subissue of https://github.com/lacona/LaconaApp/issues/21.

Phase 1 would be to allow users to customize their search paths. Phase 2 would be to have a tool that configures this automatically.

Let's keep this issue open to discuss Phase 2, and discuss Phase 1 in #21

**Comment by brandonhorst** [comment]
Implemented in [0.4.1](https://github.com/lacona/LaconaApp/blob/master/CHANGELOG.md). I've decided to support apps installed via Brew and Cask by default. Eventually, it will get an interface to manage it, which will be discussed in #21. Thanks for the report!

**Comment by agustif** [comment]
Awesome @brandonhorst I'm not yet daily active in Github but it's awesome to see I can help even if it's not yet with code!

Hope to keep up helping with wathever I can! Great project.
