### ISSUE TITLE
Can't find any files

### ISSUE THREAD

**Issue by Nxt3** [laconalabs/LaconaApp#24]
I was expecting it to function similarly to Spotlight, in the sense that I could start typing a filename and it would show me where it was and allow me to open it or open the path to it.

I can't find files at all.

I tried _open project1.pdf_, a file that I have on my system under the Dropbox folder--and it suggested I do a Google Search. I'm not 100% what the intention was--so I couldn't say if this was a bug or not. I'd really like it if it worked like Spotlight so I didn't have to type "_open filename.ext_" every time.

**Comment by brandonhorst** [comment]
Yup - this was another feature cut from this build for time reasons. Sorry about that - it will definitely be around soon.

You will be able to use the `open` command, or simply type the name of the file - if what you type doesn't match any other commands, it will use `open` by default.

**Comment by Nxt3** [comment]
Ah--no problem :) I didn't realize you had cut it out, lol.

**Comment by brandonhorst** [comment]
Implemented in [Public Beta 3](https://github.com/lacona/LaconaApp/blob/54425cbe4f04bc1ec089ff2b825ffbd047085eea/CHANGELOG.md). Thanks!

**Comment by Nxt3** [comment]
Dude, you're on fire.
