### ISSUE TITLE
Add settings page

### ISSUE THREAD

**Issue by eirnym** [laconalabs/LaconaApp#26]
Add settings page with at least following content:
 • key binding
 • theme
 • search engines customising (on/off, aliases)
 • aliases (I would like shorten 'remind me to' to 'rmt')
 • help with usage examples for every need you able to provide
 • connected plugins if you will add support to customise your engine.

**Comment by brandonhorst** [comment]
This is now implemented in [0.5.0](https://github.com/lacona/LaconaApp/blob/master/CHANGELOG.md). Aliases and plugins are not supported yet, so they are not available from the settings interface, but I'm going to close this issue out. Thank you!
