### ISSUE TITLE
play * doesn't get proper highlighting

### ISSUE THREAD

**Issue by net** [laconalabs/LaconaApp#28]
<img width="899" alt="screen shot 2016-02-01 at 9 07 35 am" src="https://cloud.githubusercontent.com/assets/6983821/12719509/5b8ff772-c8c3-11e5-8458-6426dcbac5a7.png">

**Comment by brandonhorst** [comment]
It's the same color it was before - the "action" color. 

The old version:

![image](https://cloud.githubusercontent.com/assets/1938545/12720354/6e7317ca-c8c8-11e5-8d16-5af5370b3a65.png)

I simply changed the "Action" color from blue to the default, so as to make the rest of the sentence (the arguments) stand out a bit more. I'd be interested to hear feedback, though.

**Comment by brandonhorst** [comment]
Closing this - the goal is to reduce some visual complexity, so a little less color is OK in this instance.
