### ISSUE TITLE
Bug: Switching from plugged monitor to laptop shows app outside the screen.

### ISSUE THREAD

**Issue by TigerWonder** [laconalabs/LaconaApp#29]
I have a 4k monitor that I use at home plugged into my 15" laptop. After unplugging the monitor and opening my laptop, Lacona is appearing outside the screen, instead of adapting to the new screen settings like Spotlight does, where the location is relative to the screen size. 
<img width="1440" alt="screen shot 2016-02-01 at 11 15 21 am" src="https://cloud.githubusercontent.com/assets/17009477/12724846/724040e6-c8d5-11e5-9d28-02d7304efcb7.png">

**Comment by brandonhorst** [comment]
Good find! That's nasty, I'll make sure it's fixed in the next version.

**Comment by brandonhorst** [comment]
Fixed in [Public Beta 3](https://github.com/lacona/LaconaApp/blob/54425cbe4f04bc1ec089ff2b825ffbd047085eea/CHANGELOG.md). Thanks!
