### ISSUE TITLE
A built-in dictionary query language using "define", just like Alfred

### ISSUE THREAD

**Issue by Linerd** [laconalabs/LaconaApp#30]
Sometimes if I need to find the definition for a word, it is not handy to type "translate x to lang.". I think a built-in support for apple's own dictionary app would be helpful.

**Comment by brandonhorst** [comment]
I agree that this is super-useful functionality.

**Comment by kopischke** [comment]
Though I agree on the usefulness of the functionality as such, I would be remiss not to point out that this is a Spotlight feature already.

**Comment by agustif** [comment]
@kopischke to me the whole point of these kind of apps like Lacona or Alfred is to totally replace and enhace the spotlight experience, if some query has formed an habit for spotlight users which is virtually every OS X user, and it's not available in Lacona, who will change their default ⌘+Space from Spotlight to Lacona?

For me covering basic Spotlight functionality, more importantly the one which isn't US centric, should be a priority and not overlooked.

Sadly I still don't know enough JS to shut up and do it myself...

**Comment by brandonhorst** [comment]
It's not possible yet, as the API isn't public. But it will be soon! Hopefully the docs will be good enough that you will be able to write it yourself. :smile:

**Comment by agustif** [comment]
Nice brandon, will give it a spin once they open up the API.

**Comment by brandonhorst** [comment]
Lacona Custom Addons are now available (for development only). Give it a shot! [docs.lacona.io](http://docs.lacona.io/)

**Comment by brandonhorst** [comment]
Added with [0.10.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Thanks!
