### ISSUE TITLE
Design Question: how should "Results Preview" look?

### ISSUE THREAD

**Issue by brandonhorst** [laconalabs/LaconaApp#31]
Right now, Lacona is strictly Command-Execute. That is, it shows you an interpretation of what you have entered, but it doesn't do anything until you press return.

However, for some simple features, it would be be really nice to see the results without actually needing to open anything. This is especially true for simple commands that spit out an answer in text.
- "define superlative" *
- "translate 好饿"
- "calculate 2^8" *

Alfred is a good example of this. It shows you the output, and also allows you to do things with it (copy it to your clipboard, by default)

![image](https://cloud.githubusercontent.com/assets/1938545/12735016/6f675520-c912-11e5-9b21-cc0ab2d92718.png)

Alternatively, there are times when it is good to see some non-textual representation of what you're about to do. It's helpful to see the results visually so you can process them better.
- "schedule Date for Tuesday night" *
  - (shows a calendar with a transparent event called Date at 8pm Tuesday, and the surrounding events)
- "type :+1 :" *
  - shows a preview of the :+1: emoji that it will type if you press return
- "play The Soft Bulletin"
  - shows the album art of that cd

&#42; Lacona can't actually do these things yet

Flashlight is a great example of this - it provides helpful information about what you've typed so you don't need to open a separate page.

![image](https://cloud.githubusercontent.com/assets/1938545/12735054/ad63d0f6-c912-11e5-932c-a24dca3b34c6.png)

However, I think it's important to note that these are two very different things. I'm going to call them `rich` and `plain` results. Alfred shows some `plain` results but can't show `rich` ones at all. Flashlight showed pretty much everything as `rich` results, even when it wasn't really necessary, which isn't optimal (this is a Spotlight limitation, not Flashlight!)

![image](https://cloud.githubusercontent.com/assets/1938545/12735088/eee5f004-c912-11e5-92c6-5d59f7e932bb.png)

Lacona should do this show both kinds of results. And ideally, it should to really well. The question is: how? How should the interface be laid out for maximum usability?

I'm going to post some ideas - but let me know if any thoughts immediately come to your mind.

**Comment by brandonhorst** [comment]
## Basic suggestion

This is probably the simplest solution. Doesn't mean it's bad, but it also doesn't mean it's the best.

`plain` results are displayed inline with the selected row. This would only work for short results, but it's pretty natural. If a result-less, or incomplete row is selected, nothing is shown.
- Pros:
  - Simple to implement, fairly natural to understand.
- Cons:
  - Adding more information to an already visually-complex row of text.
  - Results of any length will cause weird wrapping.

![image](https://cloud.githubusercontent.com/assets/1938545/12735323/f403bbf0-c914-11e5-8f96-0fa0fe4450cf.png)

`rich` results are displayed on the right half of the bar, like Spotlight/Flashlight, for the selected row. However, if a different row is selected the whole half of the bar goes away, and we have the normal view again.
- Pros: Doesn't show empty space when it doesn't need to.
- Cons: Interface could be jumping around a lot, especially since shrinking the rows will likely mean wrapping.

![image](https://cloud.githubusercontent.com/assets/1938545/12735417/bdccc1f2-c915-11e5-92f9-966641a36ab5.png)

Thoughts? Sorry for the very crude mockups - as the discussion goes on we can make more detailed ones.

**Comment by kopischke** [comment]
Interface functional areas jumping around would be a major UX issue. The thing about both Spotlight’s rich preview and Alfred’s plain result listings is they are consistent: QuickLook previews are **always** in the lower right Spotlight pane, the bottom list **always** consists of actionable results in Alfred. This ensures low cognitive overhead, whatever the other merits and limitations of the respective implementations.

To me, that means Lacona should never display results in a fashion changing the expected layout of parsing suggestions, no matter if rich or plain. I’d suggest a floating dedicated preview / result pane to the right (left in RTL locales) of the main UI: its floating nature and the asymmetry would reflect the optional character of the data while maintaining consistency of presentation though a reproducible layout (any of that make sense?).

**Comment by brandonhorst** [comment]
It definitely does make sense. And I agree with you. I'd love to see some animated mockups. The first thing that comes to my mind is that it would be very asymmetrical - but that may not be a bad thing.

I'll throw something together when I get the chance.

**Comment by net** [comment]
I'm a big fan of spotlight. I really wouldn't mind seeing Lacona flat out copy spotlight's style. I think it's a very clean, compact, and extendable way of displaying data.

**Comment by Nxt3** [comment]
Similar to how Spotlight does it. Even if the item doesn't need all that space--it should be easier for you to not have to worry about adjusting the layout of Lacona for different previews. Keeping it one size is the way to go.

Exactly what @net said.

**Comment by Your3xcelency** [comment]
Have you considered the following:
Display the results within the textbook where the user inputs data, like spotlight does. ignoring the bottom of the picture, look at just the text box highlighted in red:
![screen shot 2016-02-16 at 5 57 38 pm](https://cloud.githubusercontent.com/assets/17236678/13094189/325b1114-d4d7-11e5-92fd-e106dd11d0ea.png)
That would be an interesting way to provide a response. Perhaps move the result to the right of the entry and change the color to make it stand out more. Tell me what you think!

**Comment by Your3xcelency** [comment]
And for rich text results, do it like spotlight.

**Comment by Your3xcelency** [comment]
A couple more ideas. This one is for just the top bar (Instead of providing plain results on a different line, provide it like shown below.) The image below shows spotlight on top, with a (Badly Made) Design concept for Lacona below:
![screen shot 2016-02-17 at 9 52 21 am](https://cloud.githubusercontent.com/assets/17236678/13113439/1003b6da-d55d-11e5-98ad-9499f7839133.png)
You could still provide results in the rich text section as well, providing it in two locations for the user, similar to spotlight:
![screen shot 2016-02-17 at 9 59 56 am](https://cloud.githubusercontent.com/assets/17236678/13113491/3e3259bc-d55d-11e5-99c3-66a993555b58.png)
Let me know what you think!

**Comment by Nxt3** [comment]
@Your3xcelency I like the idea of how you show the calculation on the line below it--as it doesn't require having a large window for the preview.

**Comment by Kiura** [comment]
Here is a concept of lacuna UX/UI (The UI is just my preference, so could be adapted to lacona style, however personally I think its better to use short texts and icons to show actions)

The idea is to give the user instant feedback right after text area (whether it's `reach` results or `plain` or `suggestions`, user will not need to search for it (is it on the right side, or below text area) )

so, `reach` results or `plain` or `suggestions` always shown under text area.

`suggestions`:

![desktop hd](https://cloud.githubusercontent.com/assets/5522096/14125366/871fc9ee-f613-11e5-806b-ac8b93b06e6a.png)

`plain`:

![desktop hd copy 3](https://cloud.githubusercontent.com/assets/5522096/14125426/cda498fe-f613-11e5-90e2-b1ce2c71e141.png)

`rich`:

![desktop hd copy](https://cloud.githubusercontent.com/assets/5522096/14125438/e25eac1c-f613-11e5-8e89-03c03a749708.png)

Of course rich results might be disturbing if you were searching for something else, and you need to press arrow down to get other suggestion (this could be very rare case): 

![desktop hd copy 2](https://cloud.githubusercontent.com/assets/5522096/14125489/281a40ae-f614-11e5-902a-9951607cbdf1.png)

P.S. sorry for large images (open in new tab to see how it would look on mac)

**Comment by mesqueeb** [comment]
The one I would be using the most is 'gi cats' or 'g cats' for google search and google image search with results shown directly in lacona! Just like flashlight did. <3

**Comment by brandonhorst** [comment]
So I've decided to go with the solution that @kopischke suggested in [this post](https://github.com/laconalabs/LaconaApp/issues/31#issuecomment-178431323).

Here's a quick preview: 
![image](https://cloud.githubusercontent.com/assets/1938545/16440918/29c1d904-3d94-11e6-96c7-a1c4376d35a8.png)

The main reason is that _most_ commands don't require a preview of the output. "open App" and "google cats" could maybe use an icon (that's coming soon too!), but they don't need a preview of the result - it's very clear what the command is going to do, and there is no "answer".

I am shrinking the font size a bit (also visible in the screenshot) to make more room off to the side for richer outputs on smaller screens (weather is a great example, @Kiura).

The `calculate` command will come bundled with Lacona. Things like weather will be left as user commands.

This is all coming with the next release, which will probably drop next week.

With this next release, these results will not be interactive (you won't be able to click 'em), but that will hopefully be coming down the road.

What are your thoughts?

**Comment by lavaldi** [comment]
Hi, Could you select on the clipboard only one item from the preview result? if the result had many elements 🤔 

<img width="762" alt="screen shot 2017-05-20 at 7 00 45 pm" src="https://cloud.githubusercontent.com/assets/1221474/26280166/ada6790a-3d8e-11e7-864e-130ec8883373.png">
