### ISSUE TITLE
Bug: App is shown on main main display although another display is active

### ISSUE THREAD

**Issue by jcislinsky** [laconalabs/LaconaApp#32]
If I have plugged in second display and I'm working on them Lacona is shown everytime on main display – not where i am working.

It should be shown on display where Spotlight Search is showing (active display).

**Comment by brandonhorst** [comment]
Fixed in [Public Beta 3](https://github.com/lacona/LaconaApp/blob/54425cbe4f04bc1ec089ff2b825ffbd047085eea/CHANGELOG.md). Thanks!
