### ISSUE TITLE
mds_stores CPU usage 100% and up

### ISSUE THREAD

**Issue by puresick** [laconalabs/LaconaApp#34]
I recognized that the mds_stores process (Spotlight Indexing System) has a CPU usage of more than 100% when you search for something with Lacona which is unavailable.

This usage holds on until you close Lacona. 
(Sometimes the mds_stores also has such a high cpu usage even after closing Lacona, but this is not reproducable)

**Comment by brandonhorst** [comment]
Hmmm - Lacona does use Spotlight, but it doesn't control the indexing. Is it reproducible just within Lacona? What do I need to enter to "search for something with Lacona which is unavailable"?

**Comment by puresick** [comment]
I tested it with Applications which I have **not** installed (for example Photoshop) or just random characters like "ioanfiopdnsfsdi". It seems to be every time you just type in something without a parameter like "open" or "search" etc. 

It appears only with lacona - with Spotlight and Alfred I get around 20-50% of cpu usage, based on the entries and what I am looking for.

(I'm running Lacona on a 13" Macbook Pro early 2011 with El Capitain.OSX is running of a SSD which replaced the DVD Drive.)

**Comment by brandonhorst** [comment]
I was never able to reproduce this issue exactly. However, I plugged a memory leak in [Public Beta 3](https://github.com/lacona/LaconaApp/blob/54425cbe4f04bc1ec089ff2b825ffbd047085eea/CHANGELOG.md), which may have been related to this problem. After upgrading, does the problem still occur?

If the problem still occurs, it could be a problem with your Spotlight index. Could you try running `sudo mdutil -E /` from your Terminal? This command is explained [here](http://www.techradar.com/us/how-to/computing/apple/terminal-101-rebuild-the-spotlight-index-on-the-fly-1305684).

If the problem still persists, let me know and I'll need to get more system information to try and reproduce it. Thanks.

**Comment by puresick** [comment]
After upgrading to 0.4, the problem is gone. :)
Looks like it was related to the memory leak.

Great!

**Comment by brandonhorst** [comment]
Awesome!
