### ISSUE TITLE
'shutdown' command not working

### ISSUE THREAD

**Issue by puresick** [laconalabs/LaconaApp#35]
The 'shutdown' command is not working. When firing, nothing happens. 
'Sleep' etc. works well.

**Comment by brandonhorst** [comment]
Typo in the applescript! Good find.

**Comment by brandonhorst** [comment]
Fixed in [Public Beta 3](https://github.com/lacona/LaconaApp/blob/54425cbe4f04bc1ec089ff2b825ffbd047085eea/CHANGELOG.md). Thanks!
