### ISSUE TITLE
Send text command is not clear

### ISSUE THREAD

**Issue by mrvkino** [laconalabs/LaconaApp#38]
When trying to send a text the command option offered are not super clear. It might be useful to eliminate the send email or distinguish them with the colouring.

![lacona_text_example](https://cloud.githubusercontent.com/assets/279511/12805522/09823900-caca-11e5-99fe-79592a88808e.png)

Also, if the word "a" is omitted after "send" it always default to send an email with the subject "text". Compare to other command it seems to be fairly strict.

![lacona_text_email](https://cloud.githubusercontent.com/assets/279511/12805526/12d7abb6-caca-11e5-9ec1-1a04c8444675.png)

**Comment by brandonhorst** [comment]
Yeah, that needs to be cleaned up.

Are you technically inclined? You could take a look at [lacona-command-communicate](https://github.com/lacona/lacona-command-communicate/blob/master/src/index.jsx) - the changes shouldn't be too hard. Docs at [lacona/lacona](https://github.com/lacona/lacona). No tests for that command yet, unfortunately.

Of course if you can't or don't want to do it, I'll clean it up before too long.

**Comment by mrvkino** [comment]
I could look into it and see if I can do something.

**Comment by brandonhorst** [comment]
It's hard because you can make changes but you can't actually try them out yet - not a great environment for learning. But still, feel free to try it out! Sorry that all the dev infrastructure isn't in place yet.

**Comment by brandonhorst** [comment]
This was cleaned up with [0.6](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Thanks for reporting!
