### ISSUE TITLE
Application Icon

### ISSUE THREAD

**Issue by mrvkino** [laconalabs/LaconaApp#39]
It could be nice to see the application icon. Possibly the file icon also?

**Comment by brandonhorst** [comment]
It would be nice. If we were to display it, I believe that we would do it in the "results preview" area, which will come with time. If you have thoughts on the design, please check it out here:  https://github.com/lacona/LaconaApp/issues/31

**Comment by brandonhorst** [comment]
This will be present in the next released version.

**Comment by brandonhorst** [comment]
Added with [0.10.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Thanks!
