### ISSUE TITLE
Should show file vs folder

### ISSUE THREAD

**Issue by Nxt3** [laconalabs/LaconaApp#44]
When searching for files using Lacona, if there is a file and a folder with the same name--it should say "Open folder" or "Open file". For example, "micro-project1" is a folder--so it shouldn't say "file".

<img width="822" alt="screen shot 2016-02-08 at 2 20 41 pm" src="https://cloud.githubusercontent.com/assets/2940826/12896325/58e00772-ce6f-11e5-900a-0b6202dd6a28.png">

**Comment by brandonhorst** [comment]
Definitely.

**Comment by brandonhorst** [comment]
Implemented in [0.4.1](https://github.com/lacona/LaconaApp/blob/master/CHANGELOG.md).
