### ISSUE TITLE
Launching applications should have a higher priority

### ISSUE THREAD

**Issue by Nxt3** [laconalabs/LaconaApp#45]
If I search "Chrome", it should have the "Open Google Chrome" at the top of the list--as it should be a higher priority.

<img width="823" alt="screen shot 2016-02-08 at 2 27 30 pm" src="https://cloud.githubusercontent.com/assets/2940826/12896459/27bea27e-ce70-11e5-8d43-f8f9485c62dc.png">

**Comment by brandonhorst** [comment]
Ah, I see. Entries sort lower if they don't match the first word, but this shouldn't be the case for Apps.

**Comment by puresick** [comment]
Same with preference panes.

**Comment by brandonhorst** [comment]
Ack, yeah, that's pretty bad, especially since files pop up a second or two after you enter the query.

I'm gonna put out a 0.4.1 release to fix this today or tomorrow.

**Comment by Nxt3** [comment]
You da man!

**Comment by brandonhorst** [comment]
Just FYI, 0.4.1 will launch tomorrow. I decided to wrap a few other issues into it and I don't want to launch it at 1am. :smile:

**Comment by puresick** [comment]
Wow you're a machine!

**Comment by brandonhorst** [comment]
Haha, lots of features were implemented 90% when I launched the project, so just getting them to 100% is pretty easy and makes it look like progress is faster than it really is. There is a year of work behind this before the first beta!

Anyway, [0.4.1](https://github.com/lacona/LaconaApp/blob/master/CHANGELOG.md) is out, which fixes this issue!
