### ISSUE TITLE
Lacona doesn't search for Chrome Apps

### ISSUE THREAD

**Issue by Nxt3** [laconalabs/LaconaApp#46]
I have Google Keep installed as a Chrome app; Lacona doesn't find it when searching for "Keep" whereas Spotlight does.

**Comment by brandonhorst** [comment]
Yeah, these apps live in `~/Applications/` (instead of `/Applications`), so this is the same issue as https://github.com/lacona/LaconaApp/issues/21. I'm going to close this out, but this will be addressed in the next release.
