### ISSUE TITLE
Quitting application

### ISSUE THREAD

**Issue by mrvkino** [laconalabs/LaconaApp#47]
Lacona App is not able to quit applications that do not have a dock icon (ex: dropbox, better touch tool, f.lux, quicksilver, lacona, etc...). It only detect application with an activationPolicy equal to ".Regular". Dropbox and the others have an activationPolicy of ".Accessory".

I don't know how you filter the available app for the quit action, but maybe filter application with "activationPolicy" to ".Regular" and ".Accessory" so to get menubar app. Then use the bundle URL to get only  the application from /Applications and filter sub application (Google Chrome Helper.app bundleURL  has a path that is located inside of Google Chrome.app).

I am not an OS X developper, so there may be a better solution.

**Comment by brandonhorst** [comment]
Good find! The reason for this is that the "quit" and "switch to/hide/close" commands use the same source. Non-`Regular` apps can't be switched-to, hidden, or closed, but they can be quit. This logic will be expanded a bit to designate Apps "quitable, but not switchable".

**Comment by brandonhorst** [comment]
This will be available in the next release.

**Comment by brandonhorst** [comment]
Implemented in [Beta 11](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Try it out!
