### ISSUE TITLE
International character support in file search

### ISSUE THREAD

**Issue by moenia-swe** [laconalabs/LaconaApp#49]
First off, love your app Incredibly smart and easy to use. Got an issue though. I like the file searching function, although it is a bit spotty. Especially in the language department. I noticed it doesn't support international characters (like å, ä and ö in Swedish). When I try to write a word with any of those characters, it switches from wanting to open a file to searching the web for it, as soon as the Swedish letters come in.

**Comment by brandonhorst** [comment]
Should be fixed in [0.5.0](https://github.com/lacona/LaconaApp/blob/master/CHANGELOG.md). Thanks for submitting this!

**Comment by moenia-swe** [comment]
Thank YOU!
