### ISSUE TITLE
Typing "saf" too quickly shuts down computer.

### ISSUE THREAD

**Issue by Your3xcelency** [laconalabs/LaconaApp#51]
When I type "saf" too quickly (before it discovers Safari as an option) it defaults to the system command starting with s, namely shutdown. as you can imagine, this could be an issue, especially because it quits everything I have open.

**Comment by brandonhorst** [comment]
Yeah, this is a problem. We need to make sure that we process all input characters before allowing the return key.

**Comment by Your3xcelency** [comment]
BTW, I think it's great that you are putting so much of your time into this. I really respect all that you are trying to do to make Lacona a reality.

**Comment by brandonhorst** [comment]
Thanks for the kind words! Should be fixed in [0.5.0](https://github.com/lacona/LaconaApp/blob/master/CHANGELOG.md)
