### ISSUE TITLE
Request related to Plugins for Lacona Preferences:

### ISSUE THREAD

**Issue by Your3xcelency** [laconalabs/LaconaApp#54]
If possible, when you create the preferences for Lacona with support for Developer plugins, it would be great if you could create a file extension (Maybe plugin.lacona). When you click on the file, Lacona would request if you would like to install the plugin. This may help with User Friendliness - rather than a terminal package installer. (no matter how convenient it may seem to you and me, it may be too off-putting for a day to day user.) For file size, etc. you could essentially have the file being a recoded .sh or .command file, so Lacona could install the plugin on the backend. Essentially, it should be a double-click install. Just my opinion. Any other ideas, list them below!

Thanks,
Your_3xcelency

**Comment by brandonhorst** [comment]
I have never intended to have a command line package manager. When I say that it will use npm under the covers, I mean that only in the backend. I hope to have an interface in the Preferences page that will allow users to search the "database" and install commands with a click. This would be similar to how the Atom editor does plugins.

Having a file format is also nice for people downloading plugins externally (like Alfred), but I think that it's ultimately much less user-friendly then having a managed interface within the app.

You would also be able to install plugins with Natural Language commands themselves (kinda like Package Control for Sublime).

**Comment by Your3xcelency** [comment]
Cool! sounds like a great idea! Thanks for clearing that one up!

**Comment by brandonhorst** [comment]
Closing this issue. The plan is to have page within the Preferences page that allows you to download user commands. Loading them externally will not be supported (except perhaps manually, for development purposes).
