### ISSUE TITLE
Unit Conversions (20 inches in cm)

### ISSUE THREAD

**Issue by Your3xcelency** [laconalabs/LaconaApp#55]
//This (And Other) feature requests are based off of #52, and your request for me to split them into simpler, more manageable chunks//

Basic Functionality: (Things I think would be great to have before full release.)

Basic arithmetic - things like 327/4.3, as mentioned in #16.
Basic conversions - 10 inches in centimeters.
Searching by first letters of files would be great, things like typing "ftb" for "Feed the Beast", etc.

These are all functions that affect the core concept of lacona, as an App Launcher.

Thanks,
Your_3xcelency

**Comment by brandonhorst** [comment]
Basic arithmetic is in #16.

Searching by the first letter is in https://github.com/lacona/LaconaApp/issues/62.

I'll keep this open to track the request for "basic conversions".

**Comment by agustif** [comment]
Connecting this library http://mathjs.org/docs/datatypes/units.html could be helpful for live inside lacona conversions.

**Comment by brandonhorst** [comment]
:+1:

**Comment by brandonhorst** [comment]
Lacona Custom Addons are now available (for development only). Give it a shot! [docs.lacona.io](http://docs.lacona.io/)

**Comment by brandonhorst** [comment]
This has been implemented (using mathjs) for the next version. It will be automatically available upon release.

**Comment by brandonhorst** [comment]
Added with [0.10.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Thanks!
