### ISSUE TITLE
Custom sort for well known applications

### ISSUE THREAD

**Issue by revolter** [laconalabs/LaconaApp#59]
Upon trying the demo `open lacona.io in Safari and Firefox` from the website replacing it with `Chrome` like `open lacona.io in Chrome`, I get these results in this order:
- `open lacona.io in Chrome Remote Desktop`
- `open lacona.io in Chrome Connectivity Diagnostics`
- `open lacona.io in Google Chrome`

and I think that most times, one would want `Google Chrome`. Could concrete examples like this be manually "solved" in the implementation? Something like `always use "Google Chrome" when the user tries to open an url in "Chrome""`?

**Comment by brandonhorst** [comment]
I don't really like the idea of manually prescribing the sort order. I think that the best solution for this would be a "learning" mechanism like described in https://github.com/lacona/LaconaApp/issues/48. It would learn that you use "Google Chrome" much more often than other things with "Chrome" in the name, and support it first.

How does that sound?

**Comment by revolter** [comment]
Well, I don't quite like manually sort order too, but thought someone might come with a better, similar idea. As of the learning, I see two cons:
1. It's not easy, as you stated in a comment, there are some tricky use cases
2. In my example, Chrome, which is a well known browser, will still show up as the third option for (some) new users

Maybe if I rephrase it like: "Show up <browsers> as first in the list for `open url` commands". Isn't there a way to detect the installed browsers on a computer?

**Comment by brandonhorst** [comment]
This is going to be implemented on an app-by-app basis. There is simply no way to know programmatically what a "well-known application" is.

I've added support for Chrome (and a few others) in 0.10.0, which is really the biggest culprit.

At some point in the future, some sort of smart sorting may be added (https://github.com/laconalabs/LaconaApp/issues/48), but the benefits actually seem to be pretty minimal compared to the additional complexity. For the time being, if there are other apps that don't seem to sort "as expected", just let me know and we'll fix them manually.
