### ISSUE TITLE
Lacona does not recognize leap day when creating a reminder.

### ISSUE THREAD

**Issue by puresick** [laconalabs/LaconaApp#64]
A minute ago I created a reminder for tomorrow. But the reminder was added to the 2nd of March 2016. 
It seems that lacona does not recognize the leap day.

**Comment by brandonhorst** [comment]
Hmmm - it seems to work fine for me. Could you send me the exact sentence you were using?

**Comment by puresick** [comment]
The sentence was: "remind me to test tomorrow" and "remind me to buy bread tomorrow".
Today it works like it should, maybe this only happens when it's actually the leap day while creating a reminder?

**Comment by brandonhorst** [comment]
Thanks for submitting this, but I'm going to say it doesn't deserve our attention right now.

![image](https://cloud.githubusercontent.com/assets/1938545/15718504/a6a21d36-27f9-11e6-81c3-7378f85c2240.png)
