### ISSUE TITLE
Cannot open ~/ files with "open" command.

### ISSUE THREAD

**Issue by ShilohBeeler** [laconalabs/LaconaApp#65]
Exactly what the title says. I have tested "open" with applications, preference panes, volumes, URLs, folders, and files. Paths work just fine, but whenever I add the ~ in, it refuses to work correctly. It will display files and autocomplete paths, but when I hit enter to open the path, it does nothing, regardless of whether or not the application to open has been specified. Furthermore, if I then specify a second path to open, it will not open regardless of whether it is an absolute or relative path.

Thank you for taking the time to develop this, and look into this!

**Comment by brandonhorst** [comment]
Wow, what an oversight. Thanks for finding this. I'll make sure this is fixed in the next build.

I'm going to edit the title slightly - using the `~` is not a relative path per se.

**Comment by brandonhorst** [comment]
Fixed with [0.6](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Thanks for reporting!
