### ISSUE TITLE
[feature request] Currency Convertion in lacona.

### ISSUE THREAD

**Issue by agustif** [laconalabs/LaconaApp#66]
I find myself only coming back to built-in spotlight to convert prices since I'm an expat and is still hard to know day to day prices.

Maybe it would be easier to plug-in an external exchange currency API which serves JSON's the plugin can read.

Or some JS library that can be useful: http://openexchangerates.github.io/money.js/

**Comment by agustif** [comment]
I've had the idea that it also would come handy to have a way to query spotlight with the current input of Lacona, that way the project doesn't need to develop said features (Like currency convertion, weather, and others...) but just one that queries spotlight only when a combination similar to ⌘ + [Space] like ⌥ + ⌘ + [Space].

**Comment by brandonhorst** [comment]
That would make a great user command once the API is released (soon!).

The idea to open the Lacona command in spotlight is a good one, but it appears that is non-trivial to implement. After some brief searching, I cannot find a way to programmatically open Spotlight to a specific command, besides manually scripting the keystrokes, which I want to avoid as much as possible.

So for now, I'm going to say that there is a way to do that, and it is `⌘+A, ⌘+C, ⌘+Space, ⌘+V`

**Comment by brandonhorst** [comment]
Lacona Custom Addons are now available (for development only). Give it a shot! [docs.lacona.io](http://docs.lacona.io/)

**Comment by brandonhorst** [comment]
This was implemented as a user addon. It can be downloaded using 0.10.0. More info on [npm](https://www.npmjs.com/package/lacona-convert-currency)
