### ISSUE TITLE
Lacona does not remove Applications when search directories are removed

### ISSUE THREAD

**Issue by puresick** [laconalabs/LaconaApp#67]
I removed some directories in the settings panel search directories. 
Lacona seems to stop watching these directories, but keeps the applications already indexed in the search results. 

I think when you remove a directory it should also delete all the applications indexed from there.

**Comment by brandonhorst** [comment]
Should be fixed with [0.6](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Could you give it a try? Thank you!
