### ISSUE TITLE
Can't turn off Do Not Disturb

### ISSUE THREAD

**Issue by radmen** [laconalabs/LaconaApp#68]
`turn on Do Not Disturb` and `toggle Do Not Disturb` works fine, yet `turn off Do Not Disturb` does nothing.

Running Lacon public beta 6 (0.5.0) on OSX 10.11.3

**Comment by brandonhorst** [comment]
Can you test again? If you are looking at the icon in the top-right, turning off DnD does not actually change that icon, but it DOES make the notifications start happening.

![image](https://cloud.githubusercontent.com/assets/1938545/13748371/f1247c60-e9d2-11e5-8b45-f4b939284f0d.png)

This is just a quirk of the fact that DnD doesn't actually have a programmatic interface, so we need to change it with `defaults write`. Not a great solution, but it's functional. As soon as DnD gets a proper applescript or CLI interface, Lacona'll use it.

Is this the behavior that you're seeing?

**Comment by radmen** [comment]
Thanks for reply.

The answer is: not always :) When I'm not connected to any external screen command works as you wrote.

Although, when on external screen, DnD can't be disabled - OSX sticks to option "turned on while cloned".
Here's a quick video: http://screencast.com/t/MLN5OM85iSi (my system language is polish - sorry about that). 
I've tried to turn off DnD when screen is cloned (via switch in sidebar) yet it's triggered back when DnD is turned on from command.

Hope that makes sense :)

**Comment by brandonhorst** [comment]
Very interesting - I'll try to reproduce this tonight. Thanks for the detailed explanation!

**Comment by brandonhorst** [comment]
Should be fixed in Public Beta 9. 😄

**Comment by radmen** [comment]
Works. Thanks!
