### ISSUE TITLE
[Request] Choose which file types should be indexed

### ISSUE THREAD

**Issue by puresick** [laconalabs/LaconaApp#69]
Whil using lacona for a while now I noticed something which bugs me.
Everything is indexed from the locations in the settings. But I, for example, dont want certain file types and bookmarks to be indexed (because I got some other workflow for these).

It would be nice if there will be a setting to choose which data will by indexed, a bit like in spotlight.

Is this feature on your plan? :)

Keep up your great work! :+1:

**Comment by brandonhorst** [comment]
So Lacona uses the spotlight index to search for those sorts of things, so you could just remove them from Spotlight. But I imagine that you would want to keep them in spotlight for other purposes.

I see the utility in this. It may happen in the future but I'm going to treat it as low priority.
