### ISSUE TITLE
Play by song or artist doesn't do anything.

### ISSUE THREAD

**Issue by ekarious** [laconalabs/LaconaApp#70]
I tried to use `play Uprising` to launch the song from Muse but nothing happened.
When i write `play`, iTunes shows automatically and the `play current song` works nice.
But i cannot specify what i want to play.

**Comment by brandonhorst** [comment]
It works fine for me. Are you sure that the file exists (that is, when you double-click the song in iTunes, does it work)?

If the file is there, is anything logged to the Console when the failure happens? You can type `open Console` to get there.

**Comment by ekarious** [comment]
I just look into it and i saw the error in the console logs.

```
16/03/2016 15:43:59,168 Lacona[428]: __35-[ApplescriptAPI runCode:callback:]_block_invoke AppleScript task error = {
    NSAppleScriptErrorAppName = iTunes;
    NSAppleScriptErrorBriefMessage = "Can\U2019t get some track of user playlist 1 whose database ID = item 1 of {1667}.";
    NSAppleScriptErrorMessage = "iTunes got an error: Can\U2019t get some track of user playlist 1 whose database ID = item 1 of {1667}.";
    NSAppleScriptErrorNumber = "-1728";
    NSAppleScriptErrorRange = "NSRange: {314, 58}";
}, code = 
    tell application "iTunes"
      if user playlist "Lacona Playlist" exists then
        try
          delete user playlist "Lacona Playlist"
        end try
      end if

      make new user playlist with properties {name:"Lacona Playlist", shuffle: false}

      repeat with tid in {1667}
        set trk to (some track of first user playlist whose database ID is tid)
        duplicate trk to end of user playlist "Lacona Playlist"
      end repeat

      play user playlist "Lacona Playlist"
    end tell
```

Which is weird because the song plays nice directly from iTunes. I tried with other songs as well and still the same problem.

_Edit : Files are in the iTunes library and managed directly by iTunes._

**Comment by brandonhorst** [comment]
Thanks for the log.

It looks like we are collecting the iTunes database ID just fine (1667), and we are generating the play script just fine, but for some reason, the play script is no longer valid.

I suspect that the problem is the iTunes DB changed the song IDs between when the data was collected and when it was used. I _suspect_ that restarting Lacona would fix this problem. Will you let me know if that is the case?

I need to change https://github.com/laconalabs/lacona-command-itunes to ensure that the database collection is regenerated every time Lacona is activated, or at least periodically (depending on performance).

Thanks for the report.

**Comment by ekarious** [comment]
Thanks for your time !

I tried to restart it but still not working.
I got this error and i think it is the same one but, just one case, here it is !

```
16/03/2016 18:33:00,763 Lacona[4461]: __35-[ApplescriptAPI runCode:callback:]_block_invoke AppleScript task error = {
    NSAppleScriptErrorAppName = iTunes;
    NSAppleScriptErrorBriefMessage = "Can\U2019t get some track of user playlist 1 whose database ID = item 1 of {1667}.";
    NSAppleScriptErrorMessage = "iTunes got an error: Can\U2019t get some track of user playlist 1 whose database ID = item 1 of {1667}.";
    NSAppleScriptErrorNumber = "-1728";
    NSAppleScriptErrorRange = "NSRange: {314, 58}";
}, code = 
    tell application "iTunes"
      if user playlist "Lacona Playlist" exists then
        try
          delete user playlist "Lacona Playlist"
        end try
      end if

      make new user playlist with properties {name:"Lacona Playlist", shuffle: false}

      repeat with tid in {1667}
        set trk to (some track of first user playlist whose database ID is tid)
        duplicate trk to end of user playlist "Lacona Playlist"
      end repeat

      play user playlist "Lacona Playlist"
    end tell
```

**Comment by brandonhorst** [comment]
So I am **fairly sure** that this error is caused because the song exists in iTunes, but iTunes cannot actually find it on the filesystem. Otherwise, I am unable to reproduce it. Is it still occurring for you?

**Comment by ekarious** [comment]
I'll try to see if the problem still exists. If that is the case, i will open a new ticket.
Thanks for your time.
