### ISSUE TITLE
Open doesn't always work with folders

### ISSUE THREAD

**Issue by ekarious** [laconalabs/LaconaApp#71]
Like the title says, i tried to open a folder with Lacona with `open ~/Dropbox/`
but nothing showed up. I tried with another path but nothing neither. It is weird because i am sure it works this afternoon.

And no error is showing up in the console too !
I will retry tomorrow to see if i can replicate this behavior.

I am writing it in here, just in case.

**Comment by ShilohBeeler** [comment]
It's not a problem with folders, it's a problem with paths that have ~ in them. See: #65

**Comment by ekarious** [comment]
Interesting. So use the full path instead for now.

**Comment by ShilohBeeler** [comment]
Apologies for the fragmented comment, I was posting from a mobile application which I am not used to. I intended to reference #65, as it is a bug that is being worked on currently.

**Comment by ekarious** [comment]
There is no problem. I am thankful to you for your answer. I'll just wait patiently !
