### ISSUE TITLE
remind me to take out the trash at 22:00 creates unscheduled reminder

### ISSUE THREAD

**Issue by ghost** [laconalabs/LaconaApp#73]
Instead of reminding me at 22:00 a reminder gets created with the title "take out the trash at 22:00"

**Comment by brandonhorst** [comment]
[elliptical-datetime](https://github.com/laconalabs/elliptical-datetime) unfortunately does not yet support 24-hour time. Unfortunately, you will need to type "remind me to take out the trash at 10pm".

I realize that it's very American-centric of me.

Could you do me a favor and open up an issue on [elliptical-datetime](https://github.com/laconalabs/elliptical-datetime)? Thanks.
