### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by dankray** [laconalabs/LaconaApp#75]
i have contacted brandon to get to know if there are plans for translations. brandon would need support of the community, if you speak another language and have even a tiny bit of programming experience, help to spearhead that project! i will be available for german.

**Comment by brandonhorst** [comment]
Thanks @dankray.

As he said, Lacona is designed from the ground up to be translated. If commands are designed properly, they can run the same logic for every language, just with a different grammar.

However, building grammars can be much more complicated than just translating strings (like in most apps). Sentence order changes, there are special cases, and all that.

Lacona (and the underlying library [Elliptical](http://elliptical.laconalabs.com/) is designed to handle all of that, but it's a non-trivial task.

Once the public API is released, I will provide much more information about how to do translations and we will start finding people to spearhead the projects.

If you're curious now, you can take a look at a very simple grammar, like this one for [lacona-translate](https://github.com/laconalabs/lacona-translate/blob/master/src/index.jsx), which supports `translate from <language> to <language>` commands.

To give you a picture of how difficult it can be, take a look at the `Date` phrase in [elliptical-datetime](https://github.com/laconalabs/elliptical-datetime/blob/master/src/date.jsx). It is very complex, and it only supports American English.

More info to come!

**Comment by brandonhorst** [comment]
As of 1.0.2, translation is now possible! I'm going to open up a new issue to track progress and seek out translators. Get excited!
