### ISSUE TITLE
Allow repeated arguments for various setting commands.

### ISSUE THREAD

**Issue by ShilohBeeler** [laconalabs/LaconaApp#78]
I've noticed that if you want to, say, turn off bluetooth and wifi, you have to do it in two separate commands. Presumably this is because it's the setting that's the key word in the command, but whatever reason, this would be a helpful feature to have. It is, of course, a low priority request, as it's not something I frequently use.

Good luck with the development, and I'm looking forward to the developer API!

**Comment by brandonhorst** [comment]
Implemented in [Beta 11](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Try it out!
