### ISSUE TITLE
Support OSX 10.10 Yosemite

### ISSUE THREAD

**Issue by brandonhorst** [laconalabs/LaconaApp#8]
Currently, _I believe_ everything works except the global keyboard shortcut that shows Lacona. If we can make this work we can support 10.10 for users who haven't upgraded yet, or can't.

**Comment by tsimmons** [comment]
+1!!!!!

**Comment by brandonhorst** [comment]
I have looked into this and determined it to be slightly harder than I previously thought. Something is going wrong in JavascriptCore, but the error reporting from the JS world is pretty awful. I'm going to keep playing around with this, but I admit it's not a priority at this time.

**Comment by tsimmons** [comment]
Bummer, I reckon this will make the App pretty worthless for me since I cannot upgrade (due to other limitations.) Oh well, best of luck to ya!

**Comment by brandonhorst** [comment]
Implementing the settings page required me to make use of `WKWebView` - a new API that is only available in 10.11. This means that I will, unfortunately, never be able to support <=10.10.

I hope that you Yosemite folks will be able to upgrade soon! I know that it's a bummer, but with limited development resources, I need to focus on the future rather than the past. Sorry!

**Comment by tsimmons** [comment]
Thanks for the update.

Cheers.
