### ISSUE TITLE
Caffeinate Command

### ISSUE THREAD

**Issue by ghost** [laconalabs/LaconaApp#80]
> There’s a command called `caffeinated` that does exactly what the app Caffeine does — keep your computer from sleeping — but it lets you do it from scripts and the command line. [Brett Terprstra](http://brettterpstra.com/2014/02/20/quick-tip-caffeinate-your-terminal/)

`caffeinate -t 3600 &`

So in Lacona, could work like (depending on your backend code)

`caff for 1hour`

OR

`keep awake for 1hour`

**Comment by brandonhorst** [comment]
Lacona Custom Addons are now available (for development only). Give it a shot! [docs.lacona.io](http://docs.lacona.io/)

**Comment by brandonhorst** [comment]
Now available! https://www.npmjs.com/package/lacona-caffeinate
