### ISSUE TITLE
Specify Reminder List for "remind me to"/"create reminder"

### ISSUE THREAD

**Issue by brandonhorst** [laconalabs/LaconaApp#81]
Recommended on: https://twitter.com/renyygade/status/721838724930211840

Not sure about the exact language for this, what do you think?

`remind me to call Mom tomorrow in Phone Calls`
`create reminder call Mom in Phone Calls`
`add call Mom to Phone calls`

**Comment by ghost** [comment]
`remind me to call Mom tomorrow in Phone calls`

Makes the most sense based on your current syntax.

But "add" also seems nice for its simplicity.

**Comment by fiendmish** [comment]
Just trying out Lacona for the first time today and found this issue after my reminder was created in an unexpected list.

The way Siri does it you can say "add Milk to Shopping List" which is nice and simple. 

I guess the challenge for Lacuna with that is that "add" could mean any number of things (add a reminder, add a calendar event or add a note - the latter by the way would be a great addition) so you'd be changing around the point in the sentence where you specified the type of thing you were doing

**Comment by flexzuu** [comment]
And maybe add a Setting for the Default reminder List.
Because its adding the reminders to a random list that is shared with some people on my end and i can't change the default list.

**Comment by brandonhorst** [comment]
I agree that this functionality needs to be added.

The Default Reminder List is not a Lacona setting - it is a Reminders setting. You can change it in Menu Bar -> Reminders -> Default List.

**Comment by brandonhorst** [comment]
You can now do this with [1.0.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Thanks for reporting!
