### ISSUE TITLE
Multiple Web Searches, One Command

### ISSUE THREAD

**Issue by ghost** [laconalabs/LaconaApp#82]
search `ISBN#` on `Books`

`Books` then searches a group of URLs in tabs.
- Google Books
- Amazon
- Local Library catalog

I see that there's an "and command" but i'm struggling to get it work properly.

**Comment by brandonhorst** [comment]
Just to clarify, you know that right now, you could type `search isbn# on Google Books and Amazon and Local Library Catalog` right now, if those 3 searches are defined in your settings.

You are proposing the ability to add an "alias" that maps "books" to those 3 search engines.

Is that correct?

**Comment by ghost** [comment]
Ok I see that now thanks.

Yeah URL groups or multiple URLs with a separator would save a few keystrokes:

Books | `http://www.amazon.com/s?url=search-alias=aps&field-keywords=${query}&tag=lacona-20&&&https://books.google.com/search?q=${query}&&&https://www.google.com/search?q=${query}
`

Also, while working on this post I just lost all my custom URLs in the Lacona app while I was editing a URL entry.

EDIT: didn't mean to close this. sorry... -_-

**Comment by brandonhorst** [comment]
Can you describe the error you mention (your last sentence) in any more detail?

**Comment by ghost** [comment]
Unfortunately no, I think I was just editing a longer URL and clicking around on the URL list and boom, it reset.

**Comment by brandonhorst** [comment]
It reverted back to the default state? With Google -> DuckDuckGo?

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
Where's the list of URLs stored? I can TimeMachine recover.

**Comment by brandonhorst** [comment]
It's stored in `defaults`, which isn't backed up with Time Machine, unfortunately. You can run

``` sh
defaults read 'io.lacona.Lacona'
```

in the terminal and see if they're stored there.

**Comment by ghost** [comment]
That worked. Yeah, it's gone. Default list.

**Comment by brandonhorst** [comment]
Ah, I reproduced the problem. It's pretty bad - I'll fixit asap. I'll open a separate issue for it.

Sorry for losing your data! I guess that's why we have betas, huh?

**Comment by ghost** [comment]
👍 No problem. I'll probably save a text list just in case for the future.

**Comment by brandonhorst** [comment]
The bug was reported with https://github.com/laconalabs/LaconaApp/issues/83
