### ISSUE TITLE
Settings revert to default if you try to insert an empty string

### ISSUE THREAD

**Issue by brandonhorst** [laconalabs/LaconaApp#83]

**Comment by ghost** [comment]
Also you can recover via TimeMachine and restart the app. Just did. 

`/Users/NAME/Library/Preferences/io.lacona.Lacona.plist`

**Comment by brandonhorst** [comment]
Oh, awesome - didn't even know that! Thank you.

**Comment by brandonhorst** [comment]
Fixed in Beta 8.
