### ISSUE TITLE
Some call relationships missing

### ISSUE THREAD

**Issue by revolter** [laconalabs/LaconaApp#84]
When I type `call` followed by the first letter of one of my relationships, it doesn't autocomplete it. But for other relationships, it works correctly. What info should I provide to help debug this?

**Comment by brandonhorst** [comment]
In order for a relationship to appear, you must
- Have a contact card that is marked as [My Card] in the Contacts app. This will show up with a little person picture in the sidebar.

![image](https://cloud.githubusercontent.com/assets/1938545/14823471/ae189df8-0ba0-11e6-9432-48de0ed834c6.png)
- "Your Card" must have a relationship declared which references another existing contact card in such a way that clicking on the relationship brings up the `Show "First Last"` option, which when clicked, will bring up the card of the linked person.
- That person must have at least one phone number on their contact card.

If you meet all of those cases, but it doesn't show up, this is likely a bug. If I had to guess, I would assume that it has something to do with middle names or nicknames, but it's possible that it's something else.

If it is a bug, just sending me screenshots should be enough. You can black out the names if you want, but please let me know if there are any middle names or nicknames involved.

**Comment by revolter** [comment]
The second point fails for exactly the same "not working" relationships. But they were added through Siri, like the others. How can I add a relationship manually? Because it doesn't let me **select** the person, just type his name as a string.

**Comment by brandonhorst** [comment]
Yeah - from the Contacts app, there is no way to do it other than typing their name verbatim - there isn't even autocomplete.

However, we want to support Siri, so we want to know whatever is going wrong with how Siri is setting up these relationships. Is there any difference between the "name" in the relationship and the name on the contact card itself?

**Comment by revolter** [comment]
No, it's the same. The thing is that from a total of 6 relationships, 2 are not working, and both of them refer to the same person. Also, it contains `â` and an emoji. 3 of them are custom labels, including the two buggy ones. The person has a nickname set, but so does the one with the third custom label.

**Comment by revolter** [comment]
Also, when I say to Siri on my phone `call my <custom label>`, it works correctly. Another thing is that I have 2 contacts for the same "buggy" person. The second one isn't set as an relationship though, and the phone number is unprefixed.

**Comment by brandonhorst** [comment]
I suspect that the â or the emoji may be causing the problems. I'll dive into it.

**Comment by brandonhorst** [comment]
As it stands, the code will not work if the contact's first, last, or middle names have any spaces in them - do you think that is the problem?

**Comment by revolter** [comment]
It surely do have a space in the name. I'll remove it tomorrow. Also, by "the code", you are referring to Lacona or iOS/OS X Contacts?

**Comment by brandonhorst** [comment]
Lacona code. The "link a relationship name to a contact" functionality that Siri and the contacts app use is not exposed publicly, so I needed to write that code myself. Turns out it's not as robust as it needs to be.

People named "Mary Lou" or "Von Steuben" can have relationships too!

**Comment by revolter** [comment]
So is the space a definitive problem or not? And, how comes your second step about the missing menu item was correct about this contact? I mean, it looks like something is wrong in the Contacts app too.

**Comment by brandonhorst** [comment]
It's possible. I don't think we can know exactly what the Contacts app is doing under the covers - we just need code that best emulates whatever Siri does when she creates these relationships, and the algorithm isn't robust enough yet.

**Comment by revolter** [comment]
Is the code open source? Can I try to help?

**Comment by brandonhorst** [comment]
Not OSS unfortunately - I hope to make some money off a paid version eventually. (There will always be a free version of course!)

This will be fixed in the next release.

**Comment by brandonhorst** [comment]
This should be fixed in Beta 8. Let me know if it works for your use case!

**Comment by revolter** [comment]
It works now, but I found another bug.

I already had Lacona opened, and I clicked `Check for Updates...`, updated the app, clicked `Install and relaunch`, and after it opened, the update popup appeared again, even if the update was succesful.

![screen shot 2016-05-06 at 12 20 31](https://cloud.githubusercontent.com/assets/5748627/15069409/0fe58b58-1386-11e6-8d4e-e5aa9aba0d25.png)

Also, in the `About` popup, I think the build should be `0.7.0` instead of `0.7`.

**Comment by revolter** [comment]
Also, related to:

> Added support for "qualifiers" - a way of unambiguously specifying ambiguous commands. Try the call command for a contact with multiple phone numbers.

I have a contact named `X` with 2 phone numbers: `mobile` and `work`. I have it as a relationship as my `Y`.

If I type `call X`, it shows `call X (mobile)` and `call X (work)`, but if I type `call my Y`, it only shows `call my Y`

**Comment by brandonhorst** [comment]
Fixed the problem with the Autoupdater - I'll make sure that doesn't happen again!

As for the qualifiers, those haven't been implemented for Relationships yet - I'm going to open a new issue for that.
