### ISSUE TITLE
Support for partial matching in text input

### ISSUE THREAD

**Issue by notmgsk** [laconalabs/LaconaApp#85]
If I search "notes" in lacona, I will be presented with files that begin with this text. If I do the same in spotlight, I will be given many more matches as the search matches files with "notes" anywhere in the filenames.

Of course this will come with a speed cost. One way to mitigate this may be to do a "heavier" search in the background, after things like apps, files with matching beginnings, etc. have been matched. It seems this is the way spotlight works, as there isn't much of a slow down.

**Comment by ghost** [comment]
+1 I was just about to post this. 

If I am looking for a folder with the title "Archived Graphic Design" but I can only remember "Graphic Design" I am unable to find the folder and usually have to resort to spotlight.

**Comment by dv336699** [comment]
Just to add, here are the results for spotlight - not trying to compare just wanted to add some more details.

**Spotlight**
![screen shot 2016-06-08 at 07 55 55](https://cloud.githubusercontent.com/assets/930792/15892169/a2f3df94-2d4e-11e6-91bd-639d3c896e06.jpg)

**Lacona**
![screen shot 2016-06-08 at 07 56 14](https://cloud.githubusercontent.com/assets/930792/15892175/ad7901c4-2d4e-11e6-963d-c4e62a78cc50.jpg)
![screen shot 2016-06-08 at 07 56 29 1](https://cloud.githubusercontent.com/assets/930792/15892179/b22b5a00-2d4e-11e6-904b-5b24d104d1a1.jpg)

**Comment by brandonhorst** [comment]
This will be coming in the next version. Thanks!

**Comment by brandonhorst** [comment]
This was added with [0.10.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). File search now uses the same Fuzzy Matching algorithm that other Lacona features do. Let me know what you think.
