### ISSUE TITLE
Make the shortcuts behave like Spotlight

### ISSUE THREAD

**Issue by iiiGerardoiii** [laconalabs/LaconaApp#87]
It would be nice to make Lacona behave like Spotlight.
e.g.:
- If there's text on the text field, pressing Esc clears the text field, if there's no text, it closes it.
- Pressing `[Lacona Keyboard Shortcut]` after typing something on the text field will hide Lacona, and will keep the typed text in there for the next time you press `[Lacona Keyboard Shortcut]`.

Adding these features will make the user feel more familiarized with the application imo. What do you think?

**Comment by brandonhorst** [comment]
My gut tells me that there will be more people switching from Alfred than there will be switching from Spotlight, so I emulated that interface as these things are concerned.

However, perhaps my inclination is wrong. What do you all think?

**Comment by iiiGerardoiii** [comment]
Ah you're right. I'm not an Alfred user, didn't thought of that.
