### ISSUE TITLE
Saved Searches Crash on Update

### ISSUE THREAD

**Issue by ghost** [laconalabs/LaconaApp#89]
Apparently the saved searches disappeared again after the latest update. I haven't been playing with them in awhile so it wasn't triggered by the same issue as before.

**Comment by ghost** [comment]
It's overwriting on launch for some reason.

I was able to recover my .plist and replace the default, but every time Lacona launches it resets it to default.

**Comment by brandonhorst** [comment]
Diving into this now.

**Comment by brandonhorst** [comment]
Should be fixed with [Beta 11](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Hopefully that will never happen again!
