### ISSUE TITLE
Addons: <repeat><File /></repeat> performance degrades quickly

### ISSUE THREAD

**Issue by brandonhorst** [laconalabs/LaconaApp#90]
Performance becomes unusable with 3 files in sequence, and hits 30 seconds of beachball with 4.

**Comment by rben01** [comment]
Also occurs with <Directory /> and to a much lesser extent <Application /> (probably because there are so many fewer apps than files).

**Comment by brandonhorst** [comment]
This will be improved with the next release (though there are still performance improvements to be had!)

**Comment by brandonhorst** [comment]
So performance was improved with [0.10.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md), but it's still not great - it's a complicated process. I'm going to close this, but know that I am going to focus on continuing to improve perf over time.
