### ISSUE TITLE
Plays the next song instead of the currently playing

### ISSUE THREAD

**Issue by metpb** [laconalabs/LaconaApp#91]
The command `play current song` plays the next song in the playlist instead of the current song

**Comment by brandonhorst** [comment]
I can't reproduce this problem. For me, if a song is playing, `play current song` does nothing. If it's paused, it unpauses, and if no music is playing, it pretty much picks one at random. Is that not the behavior you're seeing?

**Comment by metpb** [comment]
It's funny, but I too am **not able to reproduce** the problem now. It's working as expected. 
Real sorry, man. Anyway thanks for your time.
