### ISSUE TITLE
Add option to hide menu bar icon

### ISSUE THREAD

**Issue by JohJakob** [laconalabs/LaconaApp#92]
It would be nice to have an option in Lacona's settings allowing the user to hide the menu bar icon.

**Comment by brandonhorst** [comment]
The option is available in the Lacona Preferences.
![image](https://cloud.githubusercontent.com/assets/1938545/15900217/abc47a34-2d6c-11e6-9207-8f6383c4d425.png)

**Comment by JohJakob** [comment]
@brandonhorst Oh, I'm sorry. I didn't notice it. Thanks!
