### ISSUE TITLE
Support "an" or "one" language

### ISSUE THREAD

**Issue by wootwoot1234** [laconalabs/LaconaApp#93]
When I type "remind me to call mom in an hour" or "remind me to call mom in one hour" it doesn't recognize "an" or "one" as 1.  If I type  "remind me to call mom in 1 hour" it works like icing on cake. 

Thanks guys.

**Comment by brandonhorst** [comment]
Added this with [1.0.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Thanks for reporting!
