### ISSUE TITLE
Searching through multiple bookmarks at once

### ISSUE THREAD

**Issue by andersennl** [laconalabs/LaconaApp#96]
Would it be possible to search bookmarks of e.g. Safari and Chrome at the same time, using one command? This is something that both Alfred and Spotlight can't seem to solve.

Thanks a lot for this app!

**Comment by brandonhorst** [comment]
Yeah, it's doable. Chrome bookmarks are available via Applescript, so it's not _quite_ as easy as Safari's (which are available via Spotlight) but definitely possible. I definitely want to support this.

This could be done as a User addon - it would be an Extension modeled after [lacona-osx#Bookmark](https://github.com/laconalabs/lacona-osx/blob/master/src/bookmark.jsx).

**Comment by brandonhorst** [comment]
Just released an addon called "Chrome Bookmarks" that allows Lacona to search bookmarks in Chrome. For technical reasons, it is only available for Lacona 1.0.3+, so upgrade to today's release if you haven't already.

Thank you!
