### ISSUE TITLE
Applications not being found

### ISSUE THREAD

**Issue by regularlabs** [laconalabs/LaconaApp#98]
I just installed Lacona.
It doesn't find any application I have installed.

The correct Applications path is in the settings. It doesn't find anything, not Calculator, not Chrome or Safari, nothing.

A restart of the computer did not help.

**Comment by brandonhorst** [comment]
Can you open the Apps using Spotlight?

**Comment by regularlabs** [comment]
Nope, I had Spotlight switched off, as I am currently using QuickSilver.
I disabled QuickSilver and enabled Spotlight (shortcut). But apps not
showing up in there either.

They are showing up in QuickSilver...

**Comment by brandonhorst** [comment]
So QuickSilver predates Spotlight and therefore implemented its own fancy indexing algorithm.

Lacona (and Alfred/Launchbar/etc) just make use of the Spotlight API to get the list of Applications (and Bookmarks, Files, and a few other things). So if Spotlight can't find an App, Lacona cannot find it either. This will never be changed.

First, I'd go into Spotlight setttings and make sure that Apps are being indexed. If they are, probably follow the instructions here: http://apple.stackexchange.com/questions/62715/applications-dont-show-up-in-spotlight

Once Spotlight can see Apps, Lacona should be able to too (may require a Lacona restart in some situations).

Let me know if that works for you!

**Comment by regularlabs** [comment]
Seems that all the suggested fixes I could find don't work for me.
So I can't seem to use Spotlight for starting apps, and I can't use Lacona.

**Comment by brandonhorst** [comment]
Very strange. I'm definitely no Spotlight expert unfortunately. Does your Spotlight System Preferences page look like this (more or less)?

![image](https://cloud.githubusercontent.com/assets/1938545/16304687/85411e62-3924-11e6-9db8-6e6d3e4ece87.png)
![image](https://cloud.githubusercontent.com/assets/1938545/16304692/88fa7260-3924-11e6-8049-3aea5b6954b2.png)

**Comment by regularlabs** [comment]
Yep. I even removed all checkmarks except the Application one.
The removed/disabled/enabled the Spotlight index stuff (as described in the
forums).
But still nothing.

Oh well, I'll stick to the ugly QuickSilver.

**Comment by brandonhorst** [comment]
:( May be worth talking to Apple Support about it. That's a huge bummer - that will limit your ability to use Siri for Mac too (once that is released).

Unfortunately I have no idea how to fix this - so I'm going to close this issue out. If you do figure it out, it'd be great if you could post back here and let us know. Or, if you get it working in Spotlight but it still isn't working in Lacona, please let me know and I can dive back in.

Sorry!

**Comment by regularlabs** [comment]
Finally found the answer:
http://apple.stackexchange.com/a/35073

**Comment by brandonhorst** [comment]
Super weird! I'll make sure to add that to the FAQ (once I write an FAQ). Thanks!
