### ISSUE TITLE
Commands should ignore common prefixes like "Google" and the "i" in iBooks

### ISSUE THREAD

**Issue by BenMusch** [laconalabs/LaconaApp#99]
This is more of a feature request so I'm not sure if it's the right place. It's just confusing when Google Chrome is the 8th suggestion for "Chrome"

**Comment by brandonhorst** [comment]
This will be fixed in the next version.

**Comment by brandonhorst** [comment]
Fixed with [0.10.0](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Thanks!

**Comment by brandonhorst** [comment]
One thing though - this was implemented by hardcoding a few common substitutions. If there are other apps that don't behave as-expected, let me know!
